<template><div><p>作为“为大型前端项目”而设计的前端框架，Angular 其实有许多值得参考和学习的设计，本系列主要用于研究这些设计和功能的实现原理。本文主要围绕 Angular 中的 NgZone 核心能力，这些能力主要基于 zone.js 来实现，因此本文先介绍 zone.js。</p>
<!--more-->
<p>在 Angular 中，对于数据变更检测使用的是脏检查（dirty check），这曾经在 AngularJS 版本中被诟病，认为存在性能问题。而在 Angular(2+) 版本之后，通过引入模块化组织，以及 NgZone 的设计，提升了脏检查的性能。</p>
<p>对于 NgZone 的引入，并不只是为了解决脏检查的问题，它解决了很多 Javascript 异步编程时上下文的问题，其中 zone.js 便是针对异步编程提出的作用域解决方案。</p>
<h2 id="zone-js" tabindex="-1"><a class="header-anchor" href="#zone-js" aria-hidden="true">#</a> zone.js</h2>
<p>Zone 是跨异步任务而持久存在的执行上下文，zone.js 提供以下能力：</p>
<ul>
<li>提供异步操作之间的执行上下文</li>
<li>提供异步生命周期挂钩</li>
<li>提供统一的异步错误处理机制</li>
</ul>
<h3 id="异步操作的困惑" tabindex="-1"><a class="header-anchor" href="#异步操作的困惑" aria-hidden="true">#</a> 异步操作的困惑</h3>
<p>在 Javascript 中，<a href="https://blog.sessionstack.com/how-does-javascript-actually-work-part-1-b0bacc073cf#6e11" target="_blank" rel="noopener noreferrer">代码执行过程中会产生堆栈，函数会在堆栈中执行<ExternalLinkIcon/></a>。</p>
<p>对于异步操作来说，异步代码和函数执行的时候，上下文可能发生了变化，为此可能导致一些难题。比如：</p>
<ul>
<li>异步代码执行时，上下文发生了变更，导致预期不一致</li>
<li><code v-pre>throw Error</code>时，无法准确定位到上下文</li>
<li>测试某个函数的执行耗时，但因为函数内有异步逻辑，无法得到准确的执行时间</li>
</ul>
<p>一般来说，异步代码执行时的上下文问题，可以通过传参或是全局变量的方式来解决，但两种方式都不是很优雅（尤其全局变量）。zone.js 正是为了解决以上问题而提出的，我们来看看。</p>
<h3 id="zone-js-的设计" tabindex="-1"><a class="header-anchor" href="#zone-js-的设计" aria-hidden="true">#</a> zone.js 的设计</h3>
<p>zone.js 的设计灵感来自 <a href="https://dart.dev/articles/archive/zones" target="_blank" rel="noopener noreferrer">Dart Zones<ExternalLinkIcon/></a>，你也可以将其视为 JavaScript VM 中的 <a href="https://en.wikipedia.org/wiki/Thread-local_storage" target="_blank" rel="noopener noreferrer">TLS--线程本地存储<ExternalLinkIcon/></a>。</p>
<p>zone 具有当前区域的概念：当前区域是随所有异步操作一起传播的异步上下文，它表示与当前正在执行的堆栈帧/异步任务关联的区域。</p>
<p>当前上下文可以使用<code v-pre>Zone.current</code>获取，可比作 Javascript 中的<code v-pre>this</code>，在 zone.js 中使用<code v-pre>_currentZoneFrame</code>变量跟踪当前区域。每个区域都有<code v-pre>name</code>属性，主要用于工具和调试目的，zone.js 还定义了用于操纵区域的方法：</p>
<ul>
<li><code v-pre>zone.fork(zoneSpec)</code>: 创建一个新的子区域，并将其<code v-pre>parent</code>设置为用于分支的区域</li>
<li><code v-pre>zone.run(callback, ...)</code>：在给定区域中同步调用一个函数</li>
<li><code v-pre>zone.runGuarded(callback, ...)</code>：与<code v-pre>run</code>捕获运行时错误相同，并提供了一种拦截它们的机制。如果任何父区域未处理错误，则将其重新抛出。</li>
<li><code v-pre>zone.wrap(callback)</code>：产生一个新的函数，该函数将区域绑定在一个闭包中，并在执行<code v-pre>zone.runGuarded(callback)</code>时执行，与 JavaScript 中的<code v-pre>Function.prototype.bind</code>工作原理类似。</li>
</ul>
<p>我们可以看到<code v-pre>Zone</code>的主要实现逻辑（<code v-pre>new Zone()</code>/<code v-pre>fork()</code>/<code v-pre>run()</code>）也相对简单：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">class</span> <span class="token class-name">Zone</span> <span class="token keyword">implements</span> <span class="token class-name">AmbientZone</span> <span class="token punctuation">{</span>
  <span class="token comment">// 获取根区域</span>
  <span class="token keyword">static</span> <span class="token keyword">get</span> <span class="token function">root</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> AmbientZone <span class="token punctuation">{</span>
    <span class="token keyword">let</span> zone <span class="token operator">=</span> Zone<span class="token punctuation">.</span>current<span class="token punctuation">;</span>
    <span class="token comment">// 找到最外层，父区域为自己</span>
    <span class="token keyword">while</span> <span class="token punctuation">(</span>zone<span class="token punctuation">.</span>parent<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      zone <span class="token operator">=</span> zone<span class="token punctuation">.</span>parent<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">return</span> zone<span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token comment">// 获取当前区域</span>
  <span class="token keyword">static</span> <span class="token keyword">get</span> <span class="token function">current</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> AmbientZone <span class="token punctuation">{</span>
    <span class="token keyword">return</span> _currentZoneFrame<span class="token punctuation">.</span>zone<span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token keyword">private</span> _parent<span class="token operator">:</span> Zone<span class="token operator">|</span><span class="token keyword">null</span><span class="token punctuation">;</span> <span class="token comment">// 父区域</span>
  <span class="token keyword">private</span> _name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span> <span class="token comment">// 区域名字</span>
  <span class="token keyword">private</span> _properties<span class="token operator">:</span> <span class="token punctuation">{</span><span class="token punctuation">[</span>key<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">]</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">}</span><span class="token punctuation">;</span>
  <span class="token comment">// 拦截区域操作时的委托，用于生命周期钩子相关处理</span>
  <span class="token keyword">private</span> _zoneDelegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">;</span>

  <span class="token function">constructor</span><span class="token punctuation">(</span>parent<span class="token operator">:</span> Zone<span class="token operator">|</span><span class="token keyword">null</span><span class="token punctuation">,</span> zoneSpec<span class="token operator">:</span> ZoneSpec<span class="token operator">|</span><span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// 创建区域时，设置区域的属性</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>_parent <span class="token operator">=</span> parent<span class="token punctuation">;</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>_name <span class="token operator">=</span> zoneSpec <span class="token operator">?</span> zoneSpec<span class="token punctuation">.</span>name <span class="token operator">||</span> <span class="token string">'unnamed'</span> <span class="token operator">:</span> <span class="token string">'&lt;root>'</span><span class="token punctuation">;</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>_properties <span class="token operator">=</span> zoneSpec <span class="token operator">&amp;&amp;</span> zoneSpec<span class="token punctuation">.</span>properties <span class="token operator">||</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">;</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>_zoneDelegate <span class="token operator">=</span>
        <span class="token keyword">new</span> <span class="token class-name">ZoneDelegate</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_parent <span class="token operator">&amp;&amp;</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_parent<span class="token punctuation">.</span>_zoneDelegate<span class="token punctuation">,</span> zoneSpec<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token comment">// fork 会产生子区域</span>
  <span class="token keyword">public</span> <span class="token function">fork</span><span class="token punctuation">(</span>zoneSpec<span class="token operator">:</span> ZoneSpec<span class="token punctuation">)</span><span class="token operator">:</span> AmbientZone <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>zoneSpec<span class="token punctuation">)</span> <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">Error</span><span class="token punctuation">(</span><span class="token string">'ZoneSpec required!'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">// 以当前区域为父区域，调用 new Zone() 产生子区域</span>
    <span class="token keyword">return</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_zoneDelegate<span class="token punctuation">.</span><span class="token function">fork</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> zoneSpec<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token comment">// 在区域中同步运行某段代码</span>
  <span class="token keyword">public</span> <span class="token function">run</span><span class="token punctuation">(</span>callback<span class="token operator">:</span> <span class="token builtin">Function</span><span class="token punctuation">,</span> applyThis<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> applyArgs<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> source<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">;</span>
  <span class="token keyword">public</span> <span class="token generic-function"><span class="token function">run</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>
      <span class="token function-variable function">callback</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token operator">...</span>args<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token constant">T</span><span class="token punctuation">,</span> applyThis<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> applyArgs<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> source<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span> <span class="token punctuation">{</span>
    <span class="token comment">// 准备执行，入栈处理</span>
    _currentZoneFrame <span class="token operator">=</span> <span class="token punctuation">{</span>parent<span class="token operator">:</span> _currentZoneFrame<span class="token punctuation">,</span> zone<span class="token operator">:</span> <span class="token keyword">this</span><span class="token punctuation">}</span><span class="token punctuation">;</span>
    <span class="token keyword">try</span> <span class="token punctuation">{</span>
      <span class="token comment">// 使用 callback.apply(applyThis, applyArgs) 实现</span>
      <span class="token keyword">return</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_zoneDelegate<span class="token punctuation">.</span><span class="token function">invoke</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> callback<span class="token punctuation">,</span> applyThis<span class="token punctuation">,</span> applyArgs<span class="token punctuation">,</span> source<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">finally</span> <span class="token punctuation">{</span>
      <span class="token comment">// 执行完毕，出栈处理</span>
      _currentZoneFrame <span class="token operator">=</span> _currentZoneFrame<span class="token punctuation">.</span>parent<span class="token operator">!</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
  <span class="token operator">...</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>除了上面介绍的，Zone 还提供了许多方法来运行、计划和取消任务，包括：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">interface</span> <span class="token class-name">Zone</span> <span class="token punctuation">{</span>
  <span class="token operator">...</span>
  <span class="token comment">// 通过在任务区域中恢复 Zone.currentTask 来执行任务</span>
  <span class="token generic-function"><span class="token function">runTask</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>task<span class="token operator">:</span> Task<span class="token punctuation">,</span> applyThis<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> applyArgs<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span><span class="token punctuation">;</span>
  <span class="token comment">// 安排一个 MicroTask</span>
  <span class="token function">scheduleMicroTask</span><span class="token punctuation">(</span>source<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> callback<span class="token operator">:</span> <span class="token builtin">Function</span><span class="token punctuation">,</span> data<span class="token operator">?</span><span class="token operator">:</span> TaskData<span class="token punctuation">,</span> customSchedule<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>task<span class="token operator">:</span> Task<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">)</span><span class="token operator">:</span> MicroTask<span class="token punctuation">;</span>
  <span class="token comment">// 安排一个 MacroTask</span>
  <span class="token function">scheduleMacroTask</span><span class="token punctuation">(</span>source<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> callback<span class="token operator">:</span> <span class="token builtin">Function</span><span class="token punctuation">,</span> data<span class="token operator">?</span><span class="token operator">:</span> TaskData<span class="token punctuation">,</span> customSchedule<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>task<span class="token operator">:</span> Task<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">,</span> customCancel<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>task<span class="token operator">:</span> Task<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">)</span><span class="token operator">:</span> MacroTask<span class="token punctuation">;</span>
  <span class="token comment">// 安排一个 EventTask</span>
  <span class="token function">scheduleEventTask</span><span class="token punctuation">(</span>source<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> callback<span class="token operator">:</span> <span class="token builtin">Function</span><span class="token punctuation">,</span> data<span class="token operator">?</span><span class="token operator">:</span> TaskData<span class="token punctuation">,</span> customSchedule<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>task<span class="token operator">:</span> Task<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">,</span> customCancel<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>task<span class="token operator">:</span> Task<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">)</span><span class="token operator">:</span> EventTask<span class="token punctuation">;</span>
  <span class="token comment">// 安排现有任务（对重新安排已取消的任务很有用）</span>
  <span class="token generic-function"><span class="token function">scheduleTask</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">T</span> <span class="token keyword">extends</span> Task<span class="token operator">></span></span></span><span class="token punctuation">(</span>task<span class="token operator">:</span> <span class="token constant">T</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span><span class="token punctuation">;</span>
  <span class="token comment">// 允许区域拦截计划任务的取消，使用 ZoneSpec.onCancelTask​​ 配置拦截</span>
  <span class="token function">cancelTask</span><span class="token punctuation">(</span>task<span class="token operator">:</span> Task<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="让异步逻辑运行在指定区域中" tabindex="-1"><a class="header-anchor" href="#让异步逻辑运行在指定区域中" aria-hidden="true">#</a> 让异步逻辑运行在指定区域中</h3>
<p>在 zone.js 中，通过<code v-pre>zone.fork</code>可以创建子区域，通过<code v-pre>zone.run</code>可让函数（包括函数里的异步逻辑）在指定的区域中运行。举个例子：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">const</span> zoneBC <span class="token operator">=</span> Zone<span class="token punctuation">.</span>current<span class="token punctuation">.</span><span class="token function">fork</span><span class="token punctuation">(</span><span class="token punctuation">{</span>name<span class="token operator">:</span> <span class="token string">'BC'</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">function</span> <span class="token function">c</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>Zone<span class="token punctuation">.</span>current<span class="token punctuation">.</span>name<span class="token punctuation">)</span><span class="token punctuation">;</span>  <span class="token comment">// BC</span>
<span class="token punctuation">}</span>
<span class="token keyword">function</span> <span class="token function">b</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>Zone<span class="token punctuation">.</span>current<span class="token punctuation">.</span>name<span class="token punctuation">)</span><span class="token punctuation">;</span>  <span class="token comment">// BC</span>
    <span class="token function">setTimeout</span><span class="token punctuation">(</span>c<span class="token punctuation">,</span> <span class="token number">2000</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
<span class="token keyword">function</span> <span class="token function">a</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>Zone<span class="token punctuation">.</span>current<span class="token punctuation">.</span>name<span class="token punctuation">)</span><span class="token punctuation">;</span>  <span class="token comment">// &lt;root></span>
    zoneBC<span class="token punctuation">.</span><span class="token function">run</span><span class="token punctuation">(</span>b<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token function">a</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>执行的效果如图：
<img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/angular-zone-1.png" alt=""></p>
<p>实际上，每个异步任务的调用堆栈会以根区域开始。因此，在 zone.js 中该区域会使用与任务关联的信息来还原正确的区域，然后调用该任务：</p>
<p><img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/angular-zone-2.png" alt=""></p>
<p>对于<code v-pre>Zone.fork()</code>和<code v-pre>Zone.run()</code>的作用和实现，上面已经介绍过了。那么，zone.js 是如何识别出异步任务的呢？其实 zone.js 主要是通过猴子补丁拦截异步 API（包括 DOM 事件、<code v-pre>XMLHttpRequest</code>和 NodeJS 的 API 如<code v-pre>EventEmitter</code>、<code v-pre>fs</code>等）来实现这些功能：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token comment">// 为指定的本地模块加载补丁</span>
<span class="token keyword">static</span> <span class="token function">__load_patch</span><span class="token punctuation">(</span>name<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">,</span> fn<span class="token operator">:</span> _PatchFn<span class="token punctuation">,</span> ignoreDuplicate <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span>
  <span class="token comment">// 检查是否已经加载补丁</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>patches<span class="token punctuation">.</span><span class="token function">hasOwnProperty</span><span class="token punctuation">(</span>name<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>ignoreDuplicate <span class="token operator">&amp;&amp;</span> checkDuplicate<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">throw</span> <span class="token function">Error</span><span class="token punctuation">(</span><span class="token string">'Already loaded patch: '</span> <span class="token operator">+</span> name<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token comment">// 检查是否需要加载补丁</span>
  <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>global<span class="token punctuation">[</span><span class="token string">'__Zone_disable_'</span> <span class="token operator">+</span> name<span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> perfName <span class="token operator">=</span> <span class="token string">'Zone:'</span> <span class="token operator">+</span> name<span class="token punctuation">;</span>
    <span class="token comment">// 使用 performance.mark 标记时间戳</span>
    <span class="token function">mark</span><span class="token punctuation">(</span>perfName<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">// 拦截指定异步 API，并进行相关处理</span>
    patches<span class="token punctuation">[</span>name<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token function">fn</span><span class="token punctuation">(</span>global<span class="token punctuation">,</span> Zone<span class="token punctuation">,</span> _api<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">// 使用 performance.measure 计算耗时</span>
    <span class="token function">performanceMeasure</span><span class="token punctuation">(</span>perfName<span class="token punctuation">,</span> perfName<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>以<code v-pre>setTimeout</code>等定时器为例子，通过拦截和捕获特定 API：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code>Zone<span class="token punctuation">.</span><span class="token function">__load_patch</span><span class="token punctuation">(</span><span class="token string">'timers'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span>global<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> set <span class="token operator">=</span> <span class="token string">'set'</span><span class="token punctuation">;</span>
  <span class="token keyword">const</span> clear <span class="token operator">=</span> <span class="token string">'clear'</span><span class="token punctuation">;</span>
  <span class="token function">patchTimer</span><span class="token punctuation">(</span>global<span class="token punctuation">,</span> set<span class="token punctuation">,</span> clear<span class="token punctuation">,</span> <span class="token string">'Timeout'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token function">patchTimer</span><span class="token punctuation">(</span>global<span class="token punctuation">,</span> set<span class="token punctuation">,</span> clear<span class="token punctuation">,</span> <span class="token string">'Interval'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token function">patchTimer</span><span class="token punctuation">(</span>global<span class="token punctuation">,</span> set<span class="token punctuation">,</span> clear<span class="token punctuation">,</span> <span class="token string">'Immediate'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><code v-pre>patchTimer</code>做了很多兼容性的逻辑处理，包括 Node.js 和浏览器环境的检测和处理，其中比较关键的实现逻辑在：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token comment">// 检测该函数属性是否可写</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token function">isPropertyWritable</span><span class="token punctuation">(</span>desc<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> patchDelegate <span class="token operator">=</span> <span class="token function">patchFn</span><span class="token punctuation">(</span>delegate<span class="token operator">!</span><span class="token punctuation">,</span> delegateName<span class="token punctuation">,</span> name<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">// 修改函数默认行为</span>
  proto<span class="token punctuation">[</span>name<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token function">patchDelegate</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> arguments <span class="token keyword">as</span> <span class="token builtin">any</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
  <span class="token function">attachOriginToPatched</span><span class="token punctuation">(</span>proto<span class="token punctuation">[</span>name<span class="token punctuation">]</span><span class="token punctuation">,</span> delegate<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>shouldCopySymbolProperties<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token function">copySymbolProperties</span><span class="token punctuation">(</span>delegate<span class="token punctuation">,</span> proto<span class="token punctuation">[</span>name<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token comment">// patchFn 用于使用当前的区域创建 MacroTask 任务</span>
<span class="token keyword">const</span> <span class="token function-variable function">patchFn</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span>self<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> args<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">typeof</span> args<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token operator">===</span> <span class="token string">'function'</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token operator">...</span>
    <span class="token keyword">const</span> callback <span class="token operator">=</span> args<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
    args<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token function">timer</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token operator">:</span> <span class="token builtin">unknown</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">try</span> <span class="token punctuation">{</span>
        <span class="token comment">// 执行该函数</span>
        <span class="token keyword">return</span> <span class="token function">callback</span><span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> arguments<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span> <span class="token keyword">finally</span> <span class="token punctuation">{</span>
        <span class="token comment">// 一些清理工作，比如删除任务的引用等</span>
        <span class="token punctuation">}</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">;</span>
    <span class="token comment">// 使用当前的区域创建 MacroTask 任务，调用 Zone.current.scheduleMacroTask</span>
    <span class="token keyword">const</span> task <span class="token operator">=</span> <span class="token function">scheduleMacroTaskWithCurrentZone</span><span class="token punctuation">(</span>setName<span class="token punctuation">,</span> args<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">,</span> options<span class="token punctuation">,</span> scheduleTask<span class="token punctuation">,</span> clearTask<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>task<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span> task<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token comment">// 一些兼容性处理工作，比如对于nodejs 环境，将任务引用保存在 timerId 对象中，用于 clearTimeout</span>
    <span class="token keyword">return</span> task<span class="token punctuation">;</span>
  <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
    <span class="token comment">// 出现异常时，直接返回调用</span>
    <span class="token keyword">return</span> <span class="token function">delegate</span><span class="token punctuation">.</span><span class="token function">apply</span><span class="token punctuation">(</span>window<span class="token punctuation">,</span> args<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在这里，计时器相关的 Timer 会被创建 MacroTask 任务并添加到 Zone 的任务中进行处理。在 zone.js 中，有将各种异步任务拆分为三种：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">type</span> <span class="token class-name">TaskType</span> <span class="token operator">=</span> <span class="token string">'microTask'</span><span class="token operator">|</span><span class="token string">'macroTask'</span><span class="token operator">|</span><span class="token string">'eventTask'</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>zone.js 可以支持选择性地打补丁，具体更多的补丁机制可以参考 <a href="https://github.com/angular/angular/blob/master/packages/zone.js/STANDARD-APIS.md" target="_blank" rel="noopener noreferrer">Zone.js's support for standard apis<ExternalLinkIcon/></a>。</p>
<h3 id="任务执行的生命周期" tabindex="-1"><a class="header-anchor" href="#任务执行的生命周期" aria-hidden="true">#</a> 任务执行的生命周期</h3>
<p>zone.js 提供了异步操作生命周期钩子，有了这些钩子，Zone 可以监视和拦截异步操作的所有生命周期：</p>
<ul>
<li><code v-pre>onScheduleTask</code>：此回调将在<code v-pre>async</code>操作为之前被调用<code v-pre>scheduled</code>，这意味着<code v-pre>async</code>操作即将发送到浏览器（或 NodeJS ）以计划在以后运行时</li>
<li><code v-pre>onInvokeTask</code>：此回调将在真正调用异步回调之前被调用</li>
<li><code v-pre>onHasTask</code>：当任务队列的状态在<code v-pre>empty</code>和之间更改时，将调用此回调<code v-pre>not empty</code></li>
</ul>
<p>完整的生命周期钩子包括：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">interface</span> <span class="token class-name">ZoneSpec</span> <span class="token punctuation">{</span>
  <span class="token comment">// 允许拦截 Zone.fork，对该区域进行 fork 时，请求将转发到此方法以进行拦截</span>
  onFork<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>parentZoneDelegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">,</span> currentZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> targetZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> zoneSpec<span class="token operator">:</span> ZoneSpec<span class="token punctuation">)</span> <span class="token operator">=></span> Zone<span class="token punctuation">;</span>
  <span class="token comment">// 允许拦截回调的 wrap</span>
  onIntercept<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>parentZoneDelegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">,</span> currentZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> targetZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> delegate<span class="token operator">:</span> <span class="token builtin">Function</span><span class="token punctuation">,</span> source<span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">Function</span><span class="token punctuation">;</span>
  <span class="token comment">// 允许拦截回调调用</span>
  onInvoke<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>parentZoneDelegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">,</span> currentZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> targetZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> delegate<span class="token operator">:</span> <span class="token builtin">Function</span><span class="token punctuation">,</span> applyThis<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> applyArgs<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> source<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">any</span><span class="token punctuation">;</span>
  <span class="token comment">// 允许拦截错误处理</span>
  onHandleError<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>parentZoneDelegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">,</span> currentZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> targetZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> error<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">boolean</span><span class="token punctuation">;</span>
  <span class="token comment">// 允许拦截任务计划</span>
  onScheduleTask<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>parentZoneDelegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">,</span> currentZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> targetZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> task<span class="token operator">:</span> Task<span class="token punctuation">)</span> <span class="token operator">=></span> Task<span class="token punctuation">;</span>
  <span class="token comment">// 允许拦截任务回调调用</span>
  onInvokeTask<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>parentZoneDelegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">,</span> currentZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> targetZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> task<span class="token operator">:</span> Task<span class="token punctuation">,</span> applyThis<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> applyArgs<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">any</span><span class="token punctuation">;</span>
  <span class="token comment">// 允许拦截任务取消</span>
  onCancelTask<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>parentZoneDelegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">,</span> currentZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> targetZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> task<span class="token operator">:</span> Task<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">any</span><span class="token punctuation">;</span>
  <span class="token comment">// 通知对任务队列为空状态的更改</span>
  onHasTask<span class="token operator">?</span><span class="token operator">:</span> <span class="token punctuation">(</span>parentZoneDelegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">,</span> currentZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> targetZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> hasTaskState<span class="token operator">:</span> HasTaskState<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这些生命周期的钩子回调会在<code v-pre>zone.fork()</code>时，通过<code v-pre>new Zone()</code>创建子区域并创建和传入到<code v-pre>ZoneDelegate</code>中：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">class</span> <span class="token class-name">Zone</span> <span class="token keyword">implements</span> <span class="token class-name">AmbientZone</span> <span class="token punctuation">{</span>
  <span class="token function">constructor</span><span class="token punctuation">(</span>parent<span class="token operator">:</span> Zone<span class="token operator">|</span><span class="token keyword">null</span><span class="token punctuation">,</span> zoneSpec<span class="token operator">:</span> ZoneSpec<span class="token operator">|</span><span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token operator">...</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>_zoneDelegate <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">ZoneDelegate</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_parent <span class="token operator">&amp;&amp;</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_parent<span class="token punctuation">.</span>_zoneDelegate<span class="token punctuation">,</span> zoneSpec<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>以<code v-pre>onFork</code>为例：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">class</span> <span class="token class-name">ZoneDelegate</span> <span class="token keyword">implements</span> <span class="token class-name">AmbientZoneDelegate</span> <span class="token punctuation">{</span>
  <span class="token function">constructor</span><span class="token punctuation">(</span>zone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> parentDelegate<span class="token operator">:</span> ZoneDelegate<span class="token operator">|</span><span class="token keyword">null</span><span class="token punctuation">,</span> zoneSpec<span class="token operator">:</span> ZoneSpec<span class="token operator">|</span><span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token operator">...</span>
    <span class="token comment">// 管理 onFork 钩子回调</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>_forkZS <span class="token operator">=</span> zoneSpec <span class="token operator">&amp;&amp;</span> <span class="token punctuation">(</span>zoneSpec <span class="token operator">&amp;&amp;</span> zoneSpec<span class="token punctuation">.</span>onFork <span class="token operator">?</span> zoneSpec <span class="token operator">:</span> parentDelegate<span class="token operator">!</span><span class="token punctuation">.</span>_forkZS<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>_forkDlgt <span class="token operator">=</span> zoneSpec <span class="token operator">&amp;&amp;</span> <span class="token punctuation">(</span>zoneSpec<span class="token punctuation">.</span>onFork <span class="token operator">?</span> parentDelegate <span class="token operator">:</span> parentDelegate<span class="token operator">!</span><span class="token punctuation">.</span>_forkDlgt<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>_forkCurrZone <span class="token operator">=</span>
        zoneSpec <span class="token operator">&amp;&amp;</span> <span class="token punctuation">(</span>zoneSpec<span class="token punctuation">.</span>onFork <span class="token operator">?</span> <span class="token keyword">this</span><span class="token punctuation">.</span>zone <span class="token operator">:</span> parentDelegate<span class="token operator">!</span><span class="token punctuation">.</span>_forkCurrZone<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token comment">// fork 调用时，会检查是否有 onFork 钩子回调注册，并进行调用</span>
  <span class="token function">fork</span><span class="token punctuation">(</span>targetZone<span class="token operator">:</span> Zone<span class="token punctuation">,</span> zoneSpec<span class="token operator">:</span> ZoneSpec<span class="token punctuation">)</span><span class="token operator">:</span> AmbientZone <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_forkZS <span class="token operator">?</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_forkZS<span class="token punctuation">.</span>onFork<span class="token operator">!</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>_forkDlgt<span class="token operator">!</span><span class="token punctuation">,</span> <span class="token keyword">this</span><span class="token punctuation">.</span>zone<span class="token punctuation">,</span> targetZone<span class="token punctuation">,</span> zoneSpec<span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token keyword">new</span> <span class="token class-name">Zone</span><span class="token punctuation">(</span>targetZone<span class="token punctuation">,</span> zoneSpec<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这便是 zone.js 中生命周期钩子的实现。有了这些钩子，我们可以做很多其他有用的事情，例如分析、记录和限制函数的执行和调用。</p>
<h2 id="总结" tabindex="-1"><a class="header-anchor" href="#总结" aria-hidden="true">#</a> 总结</h2>
<p>本文我们主要介绍了 zone.js，它被设计用于解决异步编程中的执行上下文问题。</p>
<p>在 zone.js 中，当前区域是随所有异步操作一起传播的异步上下文，可比作 Javascript 中的<code v-pre>this</code>。通过<code v-pre>zone.fork</code>可以创建子区域，通过<code v-pre>zone.run</code>可让函数（包括函数里的异步逻辑）在指定的区域中运行。</p>
<p>zone.js 提供了丰富的生命周期钩子，可以使用 zone.js 的区域能力以及生命周期钩子解决前面我们提到的这些问题：</p>
<ul>
<li>异步代码执行时，上下文发生了变更，导致预期不一致：使用 Zone 来执行相关代码</li>
<li><code v-pre>throw Error</code>时，无法准确定位到上下文：使用生命周期钩子<code v-pre>onHandleError</code>进行处理和跟踪</li>
<li>测试某个函数的执行耗时，但因为函数内有异步逻辑，无法得到准确的执行时间：使用生命周期钩子配合可得到具体的耗时</li>
</ul>
<h3 id="参考" tabindex="-1"><a class="header-anchor" href="#参考" aria-hidden="true">#</a> 参考</h3>
<ul>
<li><a href="https://medium.com/ngconf/deep-dive-into-zone-js-part-1-execution-context-92166bbb957" target="_blank" rel="noopener noreferrer">Deep dive into Zone.js [Part 1: Execution Context]<ExternalLinkIcon/></a></li>
<li><a href="https://medium.com/ngconf/deep-dive-into-zone-js-part-2-lifecycle-hooks-169da568227e" target="_blank" rel="noopener noreferrer">Deep dive into Zone.js [Part 2: LifeCycle Hooks]<ExternalLinkIcon/></a></li>
<li><a href="https://indepth.dev/posts/1135/i-reverse-engineered-zones-zone-js-and-here-is-what-ive-found" target="_blank" rel="noopener noreferrer">I reverse-engineered Zones (zone.js) and here is what I’ve found<ExternalLinkIcon/></a></li>
</ul>
</div></template>


