<template><div><p>作为“为大型前端项目”而设计的前端框架，Angular 其实有许多值得参考和学习的设计，本系列主要用于研究这些设计和功能的实现原理。本文主要围绕 Angular 中的 NgZone 的设计和实现来介绍。</p>
<!--more-->
<p>上一篇我们介绍了 <RouterLink to="/angular/deep-into-angular/angular-design-zonejs.html">zone.js</RouterLink>，它解决了很多 Javascript 异步编程时上下文的问题。</p>
<p>NgZone 基于 zone.js 集成了适用于 Angular 框架的一些能力。其中，对于 Angular 中的数据变更检测（脏检查）的性能优化，则主要依赖了 NgZone 的设计，我们一起来看一下。</p>
<h2 id="ngzone" tabindex="-1"><a class="header-anchor" href="#ngzone" aria-hidden="true">#</a> NgZone</h2>
<p>虽然 zone.js 可以监视同步和异步操作的所有状态，但 Angular 还提供了一项名为 NgZone 的服务。</p>
<p>NgZone 是一种用于在 Angular 区域内部或外部执行工作的可注射服务，对于不需要 Angular 处理 UI 更新或错误处理的异步任务来说，进行了性能优化的工作。</p>
<h3 id="ngzone-设计" tabindex="-1"><a class="header-anchor" href="#ngzone-设计" aria-hidden="true">#</a> NgZone 设计</h3>
<p>我们来看看 NgZone 的实现：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">NgZone</span> <span class="token punctuation">{</span>
  <span class="token keyword">readonly</span> hasPendingMacrotasks<span class="token operator">:</span> <span class="token builtin">boolean</span> <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
  <span class="token keyword">readonly</span> hasPendingMicrotasks<span class="token operator">:</span> <span class="token builtin">boolean</span> <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
  <span class="token keyword">readonly</span> isStable<span class="token operator">:</span> <span class="token builtin">boolean</span> <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
  <span class="token keyword">readonly</span> onUnstable<span class="token operator">:</span> EventEmitter<span class="token operator">&lt;</span><span class="token builtin">any</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">EventEmitter</span><span class="token punctuation">(</span><span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">readonly</span> onMicrotaskEmpty<span class="token operator">:</span> EventEmitter<span class="token operator">&lt;</span><span class="token builtin">any</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">EventEmitter</span><span class="token punctuation">(</span><span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">readonly</span> onStable<span class="token operator">:</span> EventEmitter<span class="token operator">&lt;</span><span class="token builtin">any</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">EventEmitter</span><span class="token punctuation">(</span><span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">readonly</span> onError<span class="token operator">:</span> EventEmitter<span class="token operator">&lt;</span><span class="token builtin">any</span><span class="token operator">></span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">EventEmitter</span><span class="token punctuation">(</span><span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token function">constructor</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    enableLongStackTrace <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
    shouldCoalesceEventChangeDetection <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">,</span>
    shouldCoalesceRunChangeDetection <span class="token operator">=</span> <span class="token boolean">false</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token operator">...</span>
    <span class="token comment">// 在当前区域创建子区域，作为 Angular 区域</span>
    <span class="token function">forkInnerZoneWithAngularBehavior</span><span class="token punctuation">(</span>self<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token comment">// 是否在 Angular 区域里</span>
  <span class="token keyword">static</span> <span class="token function">isInAngularZone</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">boolean</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> Zone<span class="token punctuation">.</span>current<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'isAngularZone'</span><span class="token punctuation">)</span> <span class="token operator">===</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token comment">// 在 Angular 区域内同步执行 fn 函数，并返回该函数返回的值</span>
  <span class="token comment">// 通过 run 运行可让在 Angular 区域之外执行的任务重新进入 Angular 区域</span>
  <span class="token generic-function"><span class="token function">run</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token function-variable function">fn</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token operator">...</span>args<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token constant">T</span><span class="token punctuation">,</span> applyThis<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> applyArgs<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token keyword">this</span> <span class="token keyword">as</span> <span class="token builtin">any</span> <span class="token keyword">as</span> NgZonePrivate<span class="token punctuation">)</span><span class="token punctuation">.</span>_inner<span class="token punctuation">.</span><span class="token function">run</span><span class="token punctuation">(</span>fn<span class="token punctuation">,</span> applyThis<span class="token punctuation">,</span> applyArgs<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token comment">// 在 Angular 区域内作为任务同步执行 fn 函数，并返回该函数返回的值</span>
  <span class="token generic-function"><span class="token function">runTask</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token function-variable function">fn</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token operator">...</span>args<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token constant">T</span><span class="token punctuation">,</span> applyThis<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> applyArgs<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> name<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> zone <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">this</span> <span class="token keyword">as</span> <span class="token builtin">any</span> <span class="token keyword">as</span> NgZonePrivate<span class="token punctuation">)</span><span class="token punctuation">.</span>_inner<span class="token punctuation">;</span>
    <span class="token keyword">const</span> task <span class="token operator">=</span> zone<span class="token punctuation">.</span><span class="token function">scheduleEventTask</span><span class="token punctuation">(</span><span class="token string">'NgZoneEvent: '</span> <span class="token operator">+</span> name<span class="token punctuation">,</span> fn<span class="token punctuation">,</span> <span class="token constant">EMPTY_PAYLOAD</span><span class="token punctuation">,</span> noop<span class="token punctuation">,</span> noop<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">try</span> <span class="token punctuation">{</span>
      <span class="token keyword">return</span> zone<span class="token punctuation">.</span><span class="token function">runTask</span><span class="token punctuation">(</span>task<span class="token punctuation">,</span> applyThis<span class="token punctuation">,</span> applyArgs<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">finally</span> <span class="token punctuation">{</span>
      zone<span class="token punctuation">.</span><span class="token function">cancelTask</span><span class="token punctuation">(</span>task<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
  <span class="token comment">// 与 run 相同，除了同步错误是通过 onError 捕获并转发的，而不是重新抛出</span>
  <span class="token generic-function"><span class="token function">runGuarded</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token function-variable function">fn</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token operator">...</span>args<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token constant">T</span><span class="token punctuation">,</span> applyThis<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> applyArgs<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token keyword">this</span> <span class="token keyword">as</span> <span class="token builtin">any</span> <span class="token keyword">as</span> NgZonePrivate<span class="token punctuation">)</span><span class="token punctuation">.</span>_inner<span class="token punctuation">.</span><span class="token function">runGuarded</span><span class="token punctuation">(</span>fn<span class="token punctuation">,</span> applyThis<span class="token punctuation">,</span> applyArgs<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token comment">// 在 Angular 区域外同步执行 fn 函数，并返回该函数返回的值</span>
  <span class="token generic-function"><span class="token function">runOutsideAngular</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token function-variable function">fn</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token operator">...</span>args<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token constant">T</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span> <span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token punctuation">(</span><span class="token keyword">this</span> <span class="token keyword">as</span> <span class="token builtin">any</span> <span class="token keyword">as</span> NgZonePrivate<span class="token punctuation">)</span><span class="token punctuation">.</span>_outer<span class="token punctuation">.</span><span class="token function">run</span><span class="token punctuation">(</span>fn<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>NgZone 基于 zone.js 之上再做了一层封装，通过<code v-pre>fork</code>创建出子区域作为 Angular 区域：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token function">forkInnerZoneWithAngularBehavior</span><span class="token punctuation">(</span>zone<span class="token operator">:</span> NgZonePrivate<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token operator">...</span>
  <span class="token comment">// 创建子区域，为 Angular 区域</span>
  zone<span class="token punctuation">.</span>_inner <span class="token operator">=</span> zone<span class="token punctuation">.</span>_inner<span class="token punctuation">.</span><span class="token function">fork</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    name<span class="token operator">:</span> <span class="token string">'angular'</span><span class="token punctuation">,</span>
    properties<span class="token operator">:</span> <span class="token operator">&lt;</span><span class="token builtin">any</span><span class="token operator">></span><span class="token punctuation">{</span><span class="token string-property property">'isAngularZone'</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token operator">...</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>除此之外，NgZone 里添加了用于表示没有微任务或宏任务的属性<code v-pre>isStable</code>，可用于状态的检测。另外，NgZone 还定义了四个事件：</p>
<ul>
<li><code v-pre>onUnstable</code>: 通知代码何时进入 Angular Zone，首先会在 VM Turn 上触发</li>
<li><code v-pre>onMicrotaskEmpty</code>: 通知当前的 VM Turn 中没有更多的微任务排队。这是 Angular 进行更改检测的提示，它可能会排队更多的微任务（此事件可在每次 VM 翻转时触发多次）</li>
<li><code v-pre>onStable</code>: 通知最后一个<code v-pre>onMicrotaskEmpty</code>已运行并且没有更多的微任务，这意味着即将放弃 VM 转向（此事件仅被调用一次）</li>
<li><code v-pre>onError</code>: 通知已传送错误</li>
</ul>
<p>上一节我们讲到，zone.js 处理了大多数异步 API，比如<code v-pre>setTimeout()</code>、<code v-pre>Promise.then()</code>和<code v-pre>addEventListener()</code>等。对于一些 zone.js 无法处理的第三方 API，NgZone 服务的<code v-pre>run()</code>方法可允许在 angular Zone 中执行函数。</p>
<p>通过使用 Angular Zone，函数中的所有异步操作会在正确的时间自动触发变更检测。</p>
<h3 id="自动触发变更检测" tabindex="-1"><a class="header-anchor" href="#自动触发变更检测" aria-hidden="true">#</a> 自动触发变更检测</h3>
<p>当 NgZone 满足以下条件时，会创建一个名为 angular 的 Zone 来自动触发变更检测：</p>
<ul>
<li>当执行同步或异步功能时（zone.js 内置变更检测，最终会通过<code v-pre>onMicrotaskEmpty</code>来触发）</li>
<li>已经没有已计划的 Microtask（<code v-pre>onMicrotaskEmpty</code>）</li>
</ul>
<p><code v-pre>onMicrotaskEmpty</code>条件的触发监听，以及检测逻辑位于<code v-pre>ApplicationRef</code>中：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token decorator"><span class="token at operator">@</span><span class="token function">Injectable</span></span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">ApplicationRef</span> <span class="token punctuation">{</span>
  <span class="token operator">...</span>
  <span class="token function">constructor</span><span class="token punctuation">(</span>
      <span class="token keyword">private</span> _zone<span class="token operator">:</span> NgZone<span class="token punctuation">,</span> <span class="token keyword">private</span> _injector<span class="token operator">:</span> Injector<span class="token punctuation">,</span> <span class="token keyword">private</span> _exceptionHandler<span class="token operator">:</span> ErrorHandler<span class="token punctuation">,</span>
      <span class="token keyword">private</span> _componentFactoryResolver<span class="token operator">:</span> ComponentFactoryResolver<span class="token punctuation">,</span>
      <span class="token keyword">private</span> _initStatus<span class="token operator">:</span> ApplicationInitStatus<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// Microtask 为空时，触发变更检测</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>_onMicrotaskEmptySubscription <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_zone<span class="token punctuation">.</span>onMicrotaskEmpty<span class="token punctuation">.</span><span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
      <span class="token function-variable function">next</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span>_zone<span class="token punctuation">.</span><span class="token function">run</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
          <span class="token comment">// tick 为变更检测的逻辑，会重新进行 template 的计算和渲染</span>
          <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">tick</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token operator">...</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们来看看，在什么时候会触发<code v-pre>onMicrotaskEmpty</code>事件：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token function">checkStable</span><span class="token punctuation">(</span>zone<span class="token operator">:</span> NgZonePrivate<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>zone<span class="token punctuation">.</span>_nesting <span class="token operator">==</span> <span class="token number">0</span> <span class="token operator">&amp;&amp;</span> <span class="token operator">!</span>zone<span class="token punctuation">.</span>hasPendingMicrotasks <span class="token operator">&amp;&amp;</span> <span class="token operator">!</span>zone<span class="token punctuation">.</span>isStable<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">try</span> <span class="token punctuation">{</span>
      zone<span class="token punctuation">.</span>_nesting<span class="token operator">++</span><span class="token punctuation">;</span>
      zone<span class="token punctuation">.</span>onMicrotaskEmpty<span class="token punctuation">.</span><span class="token function">emit</span><span class="token punctuation">(</span><span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">finally</span> <span class="token punctuation">{</span>
      zone<span class="token punctuation">.</span>_nesting<span class="token operator">--</span><span class="token punctuation">;</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>zone<span class="token punctuation">.</span>hasPendingMicrotasks<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">try</span> <span class="token punctuation">{</span>
          zone<span class="token punctuation">.</span><span class="token function">runOutsideAngular</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> zone<span class="token punctuation">.</span>onStable<span class="token punctuation">.</span><span class="token function">emit</span><span class="token punctuation">(</span><span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">finally</span> <span class="token punctuation">{</span>
          zone<span class="token punctuation">.</span>isStable <span class="token operator">=</span> <span class="token boolean">true</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当<code v-pre>onInvokeTask</code>和<code v-pre>onInvoke</code>两个钩子被触发时，微任务队列中可能会发生变化，因此 Angular 必须在每次钩子被触发时运行检查。除此之外，<code v-pre>onHasTask</code>挂钩还用于执行检查，因为它跟踪整个队列更改：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token function">forkInnerZoneWithAngularBehavior</span><span class="token punctuation">(</span>zone<span class="token operator">:</span> NgZonePrivate<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> <span class="token function-variable function">delayChangeDetectionForEventsDelegate</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token comment">// delayChangeDetectionForEvents 内部调用了 checkStable()</span>
    <span class="token function">delayChangeDetectionForEvents</span><span class="token punctuation">(</span>zone<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
  zone<span class="token punctuation">.</span>_inner <span class="token operator">=</span> zone<span class="token punctuation">.</span>_inner<span class="token punctuation">.</span><span class="token function">fork</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token operator">...</span>
    onInvokeTask<span class="token operator">:</span>
        <span class="token punctuation">(</span>delegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">,</span> current<span class="token operator">:</span> Zone<span class="token punctuation">,</span> target<span class="token operator">:</span> Zone<span class="token punctuation">,</span> task<span class="token operator">:</span> Task<span class="token punctuation">,</span> applyThis<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> applyArgs<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">any</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
          <span class="token operator">...</span>
          <span class="token comment">// 进行检测</span>
          <span class="token function">delayChangeDetectionForEventsDelegate</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>

    onInvoke<span class="token operator">:</span>
        <span class="token punctuation">(</span>delegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">,</span> current<span class="token operator">:</span> Zone<span class="token punctuation">,</span> target<span class="token operator">:</span> Zone<span class="token punctuation">,</span> callback<span class="token operator">:</span> <span class="token builtin">Function</span><span class="token punctuation">,</span> applyThis<span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">,</span> applyArgs<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">any</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> source<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">any</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
          <span class="token operator">...</span>
          <span class="token comment">// 进行检测</span>
          <span class="token function">delayChangeDetectionForEventsDelegate</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>

    <span class="token function-variable function">onHasTask</span><span class="token operator">:</span>
        <span class="token punctuation">(</span>delegate<span class="token operator">:</span> ZoneDelegate<span class="token punctuation">,</span> current<span class="token operator">:</span> Zone<span class="token punctuation">,</span> target<span class="token operator">:</span> Zone<span class="token punctuation">,</span> hasTaskState<span class="token operator">:</span> HasTaskState<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
          <span class="token operator">...</span>
          <span class="token keyword">if</span> <span class="token punctuation">(</span>current <span class="token operator">===</span> target<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token comment">// 只检查当前区域的任务</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>hasTaskState<span class="token punctuation">.</span>change <span class="token operator">==</span> <span class="token string">'microTask'</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
              zone<span class="token punctuation">.</span>_hasPendingMicrotasks <span class="token operator">=</span> hasTaskState<span class="token punctuation">.</span>microTask<span class="token punctuation">;</span>
              <span class="token function">updateMicroTaskStatus</span><span class="token punctuation">(</span>zone<span class="token punctuation">)</span><span class="token punctuation">;</span>
              <span class="token comment">// 跟踪 MicroTask 队列，并进行检查</span>
              <span class="token function">checkStable</span><span class="token punctuation">(</span>zone<span class="token punctuation">)</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            <span class="token operator">...</span>
          <span class="token punctuation">}</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>默认情况下，所有异步操作都在 Angular Zone 内，这会自动触发变更检测。</p>
<p>另一个常见的情况是我们不想触发变更检测（比如不希望像<code v-pre>scroll</code>等事件过于频繁地进行变更检测，从而导致性能问题），此时可以使用 NgZone 的<code v-pre>runOutsideAngular()</code>方法。</p>
<p>zone.js 能帮助 Angular 知道何时要触发变更检测，使得开发人员专注于应用开发。默认情况下，zone.js 已加载且无需其他配置即可工作。如果希望选择自己触发变更检测，则可以通过禁用 zone.js 的方式来处理。</p>
<h2 id="总结" tabindex="-1"><a class="header-anchor" href="#总结" aria-hidden="true">#</a> 总结</h2>
<p>本文介绍了 NgZone 在 zone.js 的基础上进行了封装，从而使得在 Angular Zone 内函数中的所有异步操作可以在正确的时间自动触发变更检测。</p>
<p>可以根据自身的需要，使用 NgZone 的<code v-pre>runOutsideAngular()</code>方法减少变更检测，也可以通过禁用 zone.js 的方式，来自己实现变更检测的逻辑。</p>
<h3 id="参考" tabindex="-1"><a class="header-anchor" href="#参考" aria-hidden="true">#</a> 参考</h3>
<ul>
<li><a href="https://angular.cn/guide/zone" target="_blank" rel="noopener noreferrer">Angular-NgZone<ExternalLinkIcon/></a></li>
<li><a href="https://indepth.dev/posts/1059/do-you-still-think-that-ngzone-zone-js-is-required-for-change-detection-in-angular" target="_blank" rel="noopener noreferrer">Do you still think that NgZone (zone.js) is required for change detection in Angular?<ExternalLinkIcon/></a></li>
</ul>
</div></template>


