<template><div><p>作为“为大型前端项目”而设计的前端框架，Angular 其实有许多值得参考和学习的设计，本系列主要用于研究这些设计和功能的实现原理。本文主要围绕 Angular 中的最大特点——依赖注入，介绍 Angular 依赖注入在体系在应用引导过程中的的设计和实现。</p>
<!--more-->
<p><RouterLink to="/angular/deep-into-angular/angular-design-di-2-hierarchical-di.html">多级依赖注入</RouterLink>中，介绍了模块注入器和元素注入器两种层次结构的注入器。那么，Angular 在引导过程中，又是如何初始化根模块和入口组件的呢？</p>
<h1 id="angular-的引导过程" tabindex="-1"><a class="header-anchor" href="#angular-的引导过程" aria-hidden="true">#</a> Angular 的引导过程</h1>
<p>前面我们说到，Angular 应用在浏览器中引导时，会创建浏览器平台，并引导根模块：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token function">platformBrowserDynamic</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">bootstrapModule</span><span class="token punctuation">(</span>AppModule<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="引导根模块" tabindex="-1"><a class="header-anchor" href="#引导根模块" aria-hidden="true">#</a> 引导根模块</h2>
<h3 id="根模块-appmodule" tabindex="-1"><a class="header-anchor" href="#根模块-appmodule" aria-hidden="true">#</a> 根模块 AppModule</h3>
<p>在 Angular 中，每个应用有至少一个 Angular 模块，根模块就是你用来引导此应用的模块，它通常命名为 AppModule。</p>
<p>当你使用 Angular CLI 命令 ng new 生成一个应用时，其默认的 AppModule 是这样的：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> BrowserModule <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@angular/platform-browser'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> NgModule <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@angular/core'</span><span class="token punctuation">;</span>

<span class="token keyword">import</span> <span class="token punctuation">{</span> AppComponent <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'./app.component'</span><span class="token punctuation">;</span>

<span class="token decorator"><span class="token at operator">@</span><span class="token function">NgModule</span></span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  declarations<span class="token operator">:</span> <span class="token punctuation">[</span>
    AppComponent
  <span class="token punctuation">]</span><span class="token punctuation">,</span>
  imports<span class="token operator">:</span> <span class="token punctuation">[</span>
    BrowserModule
  <span class="token punctuation">]</span><span class="token punctuation">,</span>
  providers<span class="token operator">:</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
  bootstrap<span class="token operator">:</span> <span class="token punctuation">[</span>AppComponent<span class="token punctuation">]</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">AppModule</span> <span class="token punctuation">{</span> <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="引导根模块的过程" tabindex="-1"><a class="header-anchor" href="#引导根模块的过程" aria-hidden="true">#</a> 引导根模块的过程</h3>
<p>我们来看看平台层引导根模块的过程中都做了些什么：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token decorator"><span class="token at operator">@</span><span class="token function">Injectable</span></span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">PlatformRef</span> <span class="token punctuation">{</span>
  <span class="token operator">...</span>

  <span class="token generic-function"><span class="token function">bootstrapModuleFactory</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">M</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>moduleFactory<span class="token operator">:</span> NgModuleFactory<span class="token operator">&lt;</span><span class="token constant">M</span><span class="token operator">></span><span class="token punctuation">,</span> options<span class="token operator">?</span><span class="token operator">:</span> BootstrapOptions<span class="token punctuation">)</span><span class="token operator">:</span>
      <span class="token builtin">Promise</span><span class="token operator">&lt;</span>NgModuleRef<span class="token operator">&lt;</span><span class="token constant">M</span><span class="token operator">>></span> <span class="token punctuation">{</span>
    <span class="token comment">// 由于实例化模块时，会需要创建一些提供者，所以这里需要在实例化模块之前创建 NgZone</span>
    <span class="token comment">// 因此，这里创建了一个仅包含新 NgZone 的微型父注入器，并将其作为父传递给 NgModuleFactory</span>
    <span class="token keyword">const</span> ngZoneOption <span class="token operator">=</span> options <span class="token operator">?</span> options<span class="token punctuation">.</span>ngZone <span class="token operator">:</span> <span class="token keyword">undefined</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> ngZoneEventCoalescing <span class="token operator">=</span> <span class="token punctuation">(</span>options <span class="token operator">&amp;&amp;</span> options<span class="token punctuation">.</span>ngZoneEventCoalescing<span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> ngZoneRunCoalescing <span class="token operator">=</span> <span class="token punctuation">(</span>options <span class="token operator">&amp;&amp;</span> options<span class="token punctuation">.</span>ngZoneRunCoalescing<span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> ngZone <span class="token operator">=</span> <span class="token function">getNgZone</span><span class="token punctuation">(</span>ngZoneOption<span class="token punctuation">,</span> <span class="token punctuation">{</span>ngZoneEventCoalescing<span class="token punctuation">,</span> ngZoneRunCoalescing<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> providers<span class="token operator">:</span> StaticProvider<span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">{</span>provide<span class="token operator">:</span> NgZone<span class="token punctuation">,</span> useValue<span class="token operator">:</span> ngZone<span class="token punctuation">}</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
    <span class="token comment">// ApplicationRef 将在 Angular zone 之外创建</span>
    <span class="token keyword">return</span> ngZone<span class="token punctuation">.</span><span class="token function">run</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token comment">// 在 ngZone.run 中创建 ngZoneInjector，以便在 Angular zone 中创建所有实例化的服务</span>
      <span class="token keyword">const</span> ngZoneInjector <span class="token operator">=</span> Injector<span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span>
          <span class="token punctuation">{</span>providers<span class="token operator">:</span> providers<span class="token punctuation">,</span> parent<span class="token operator">:</span> <span class="token keyword">this</span><span class="token punctuation">.</span>injector<span class="token punctuation">,</span> name<span class="token operator">:</span> moduleFactory<span class="token punctuation">.</span>moduleType<span class="token punctuation">.</span>name<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">const</span> moduleRef <span class="token operator">=</span> <span class="token operator">&lt;</span>InternalNgModuleRef<span class="token operator">&lt;</span><span class="token constant">M</span><span class="token operator">>></span>moduleFactory<span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span>ngZoneInjector<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">const</span> exceptionHandler<span class="token operator">:</span> ErrorHandler<span class="token operator">|</span><span class="token keyword">null</span> <span class="token operator">=</span> moduleRef<span class="token punctuation">.</span>injector<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>ErrorHandler<span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>exceptionHandler<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">Error</span><span class="token punctuation">(</span><span class="token string">'No ErrorHandler. Is platform module (BrowserModule) included?'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
      <span class="token operator">...</span>
      <span class="token keyword">return</span> <span class="token function">_callAndReportToErrorHandler</span><span class="token punctuation">(</span>exceptionHandler<span class="token punctuation">,</span> ngZone<span class="token operator">!</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token keyword">const</span> initStatus<span class="token operator">:</span> ApplicationInitStatus <span class="token operator">=</span> moduleRef<span class="token punctuation">.</span>injector<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>ApplicationInitStatus<span class="token punctuation">)</span><span class="token punctuation">;</span>
        initStatus<span class="token punctuation">.</span><span class="token function">runInitializers</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> initStatus<span class="token punctuation">.</span>donePromise<span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
          <span class="token operator">...</span>
          <span class="token comment">// 引导模块</span>
          <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">_moduleDoBootstrap</span><span class="token punctuation">(</span>moduleRef<span class="token punctuation">)</span><span class="token punctuation">;</span>
          <span class="token keyword">return</span> moduleRef<span class="token punctuation">;</span>
        <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

  <span class="token generic-function"><span class="token function">bootstrapModule</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">M</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>
      moduleType<span class="token operator">:</span> Type<span class="token operator">&lt;</span><span class="token constant">M</span><span class="token operator">></span><span class="token punctuation">,</span>
      compilerOptions<span class="token operator">:</span> <span class="token punctuation">(</span>CompilerOptions<span class="token operator">&amp;</span>BootstrapOptions<span class="token punctuation">)</span><span class="token operator">|</span>
      <span class="token builtin">Array</span><span class="token operator">&lt;</span>CompilerOptions<span class="token operator">&amp;</span>BootstrapOptions<span class="token operator">></span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>NgModuleRef<span class="token operator">&lt;</span><span class="token constant">M</span><span class="token operator">>></span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> options <span class="token operator">=</span> <span class="token function">optionsReducer</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span> compilerOptions<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">// 编译并创建 @NgModule 的实例</span>
    <span class="token keyword">return</span> <span class="token function">compileNgModuleFactory</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>injector<span class="token punctuation">,</span> options<span class="token punctuation">,</span> moduleType<span class="token punctuation">)</span>
        <span class="token punctuation">.</span><span class="token function">then</span><span class="token punctuation">(</span>moduleFactory <span class="token operator">=></span> <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">bootstrapModuleFactory</span><span class="token punctuation">(</span>moduleFactory<span class="token punctuation">,</span> options<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>

  <span class="token keyword">private</span> <span class="token function">_moduleDoBootstrap</span><span class="token punctuation">(</span>moduleRef<span class="token operator">:</span> InternalNgModuleRef<span class="token operator">&lt;</span><span class="token builtin">any</span><span class="token operator">></span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> appRef <span class="token operator">=</span> moduleRef<span class="token punctuation">.</span>injector<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>ApplicationRef<span class="token punctuation">)</span> <span class="token keyword">as</span> ApplicationRef<span class="token punctuation">;</span>
    <span class="token comment">// 引导应用程序</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>moduleRef<span class="token punctuation">.</span>_bootstrapComponents<span class="token punctuation">.</span>length <span class="token operator">></span> <span class="token number">0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token comment">// 在应用程序的根级别引导新组件</span>
      moduleRef<span class="token punctuation">.</span>_bootstrapComponents<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span>f <span class="token operator">=></span> appRef<span class="token punctuation">.</span><span class="token function">bootstrap</span><span class="token punctuation">(</span>f<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>moduleRef<span class="token punctuation">.</span>instance<span class="token punctuation">.</span>ngDoBootstrap<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      moduleRef<span class="token punctuation">.</span>instance<span class="token punctuation">.</span><span class="token function">ngDoBootstrap</span><span class="token punctuation">(</span>appRef<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
      <span class="token operator">...</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span>_modules<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>moduleRef<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>根模块引导时，除了编译并创建 AppModule 的实例，还会创建 NgZone，关于 NgZone 的请参考<a href=""></a>。在编译和创建 AppModule 的过程中，便会创建<code v-pre>ApplicationRef</code>，即 Angular 应用程序。</p>
<h2 id="引导-angular-应用程序" tabindex="-1"><a class="header-anchor" href="#引导-angular-应用程序" aria-hidden="true">#</a> 引导 Angular 应用程序</h2>
<p>前面在引导根模块过程中，创建了 Angular 应用程序之后，便会在应用程序的根级别引导新组件：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token comment">// 在应用程序的根级别引导新组件</span>
moduleRef<span class="token punctuation">.</span>_bootstrapComponents<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span>f <span class="token operator">=></span> appRef<span class="token punctuation">.</span><span class="token function">bootstrap</span><span class="token punctuation">(</span>f<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>我们来看看这个过程会发生什么。</p>
<h3 id="应用程序-applicationref" tabindex="-1"><a class="header-anchor" href="#应用程序-applicationref" aria-hidden="true">#</a> 应用程序 ApplicationRef</h3>
<p>一个 Angular 应用程序，提供了以下的能力：</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token decorator"><span class="token at operator">@</span><span class="token function">Injectable</span></span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">ApplicationRef</span> <span class="token punctuation">{</span>
  <span class="token comment">// 获取已注册到该应用程序的组件类型的列表</span>
  <span class="token keyword">public</span> <span class="token keyword">readonly</span> componentTypes<span class="token operator">:</span> Type<span class="token operator">&lt;</span><span class="token builtin">any</span><span class="token operator">></span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token comment">// 获取已注册到该应用程序的组件的列表</span>
  <span class="token keyword">public</span> <span class="token keyword">readonly</span> components<span class="token operator">:</span> ComponentRef<span class="token operator">&lt;</span><span class="token builtin">any</span><span class="token operator">></span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  <span class="token comment">// 返回一个 Observable，指示应用程序何时稳定或不稳定</span>
  <span class="token comment">// 如果在应用程序引导时，引导任何种类的周期性异步任务，则该应用程序将永远不会稳定（例如轮询过程）</span>
  <span class="token keyword">public</span> <span class="token keyword">readonly</span> isStable<span class="token operator">!</span><span class="token operator">:</span> Observable<span class="token operator">&lt;</span><span class="token builtin">boolean</span><span class="token operator">></span><span class="token punctuation">;</span>

  <span class="token function">constructor</span><span class="token punctuation">(</span>
      <span class="token keyword">private</span> _zone<span class="token operator">:</span> NgZone<span class="token punctuation">,</span> <span class="token keyword">private</span> _injector<span class="token operator">:</span> Injector<span class="token punctuation">,</span> <span class="token keyword">private</span> _exceptionHandler<span class="token operator">:</span> ErrorHandler<span class="token punctuation">,</span>
      <span class="token keyword">private</span> _componentFactoryResolver<span class="token operator">:</span> ComponentFactoryResolver<span class="token punctuation">,</span>
      <span class="token keyword">private</span> _initStatus<span class="token operator">:</span> ApplicationInitStatus<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// 创建时，主要进行两件事：</span>
        <span class="token comment">// 1. 宏任务结束后，检测视图是否需要更新。</span>
        <span class="token comment">// 2. 在 Angular Zone 之外创建对 onStable 的预订，以便在 Angular Zone 之外运行回调。</span>
  <span class="token punctuation">}</span>
  <span class="token comment">// 在应用程序的根级别引导新组件</span>
  <span class="token generic-function"><span class="token function">bootstrap</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">C</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>componentOrFactory<span class="token operator">:</span> ComponentFactory<span class="token operator">&lt;</span><span class="token constant">C</span><span class="token operator">></span><span class="token operator">|</span>Type<span class="token operator">&lt;</span><span class="token constant">C</span><span class="token operator">></span><span class="token punctuation">,</span> rootSelectorOrNode<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token operator">|</span><span class="token builtin">any</span><span class="token punctuation">)</span><span class="token operator">:</span>
      ComponentRef<span class="token operator">&lt;</span><span class="token constant">C</span><span class="token operator">></span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
  <span class="token comment">// 调用此方法以显式处理更改检测及其副作用</span>
  <span class="token function">tick</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
  <span class="token comment">// 关联视图，以便对其进行脏检查，视图销毁后将自动分离</span>
  <span class="token function">attachView</span><span class="token punctuation">(</span>viewRef<span class="token operator">:</span> ViewRef<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
  <span class="token comment">// 再次从脏检查中分离视图</span>
  <span class="token function">detachView</span><span class="token punctuation">(</span>viewRef<span class="token operator">:</span> ViewRef<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>那么，我们来看看<code v-pre>bootstrap()</code>过程中，Angular 都做了些什么。</p>
<h3 id="在应用程序的根级别引导根组件" tabindex="-1"><a class="header-anchor" href="#在应用程序的根级别引导根组件" aria-hidden="true">#</a> 在应用程序的根级别引导根组件</h3>
<p>将新的根组件引导到应用程序中时，Angular 将指定的应用程序组件安装到由<code v-pre>componentType</code>的选择器标识的 DOM 元素上，并引导自动更改检测以完成组件的初始化。</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token decorator"><span class="token at operator">@</span><span class="token function">Injectable</span></span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">ApplicationRef</span> <span class="token punctuation">{</span>
  <span class="token generic-function"><span class="token function">bootstrap</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">C</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>componentOrFactory<span class="token operator">:</span> ComponentFactory<span class="token operator">&lt;</span><span class="token constant">C</span><span class="token operator">></span><span class="token operator">|</span>Type<span class="token operator">&lt;</span><span class="token constant">C</span><span class="token operator">></span><span class="token punctuation">,</span> rootSelectorOrNode<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token operator">|</span><span class="token builtin">any</span><span class="token punctuation">)</span><span class="token operator">:</span>
      ComponentRef<span class="token operator">&lt;</span><span class="token constant">C</span><span class="token operator">></span> <span class="token punctuation">{</span>
    <span class="token operator">...</span>
    <span class="token comment">// 如果未与其他模块绑定，则创建与当前模块关联的工厂</span>
    <span class="token keyword">const</span> ngModule <span class="token operator">=</span>
        <span class="token function">isBoundToModule</span><span class="token punctuation">(</span>componentFactory<span class="token punctuation">)</span> <span class="token operator">?</span> <span class="token keyword">undefined</span> <span class="token operator">:</span> <span class="token keyword">this</span><span class="token punctuation">.</span>_injector<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>NgModuleRef<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> selectorOrNode <span class="token operator">=</span> rootSelectorOrNode <span class="token operator">||</span> componentFactory<span class="token punctuation">.</span>selector<span class="token punctuation">;</span>
    <span class="token comment">// 创建组件</span>
    <span class="token keyword">const</span> compRef <span class="token operator">=</span> componentFactory<span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span>Injector<span class="token punctuation">.</span><span class="token constant">NULL</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> selectorOrNode<span class="token punctuation">,</span> ngModule<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> nativeElement <span class="token operator">=</span> compRef<span class="token punctuation">.</span>location<span class="token punctuation">.</span>nativeElement<span class="token punctuation">;</span>
    <span class="token comment">// 创建可测试服务挂钩</span>
    <span class="token keyword">const</span> testability <span class="token operator">=</span> compRef<span class="token punctuation">.</span>injector<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>Testability<span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">const</span> testabilityRegistry <span class="token operator">=</span> testability <span class="token operator">&amp;&amp;</span> compRef<span class="token punctuation">.</span>injector<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span>TestabilityRegistry<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>testability <span class="token operator">&amp;&amp;</span> testabilityRegistry<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      testabilityRegistry<span class="token punctuation">.</span><span class="token function">registerApplication</span><span class="token punctuation">(</span>nativeElement<span class="token punctuation">,</span> testability<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token comment">// 组件销毁时，销毁关联视图以及相关的服务</span>
    compRef<span class="token punctuation">.</span><span class="token function">onDestroy</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">detachView</span><span class="token punctuation">(</span>compRef<span class="token punctuation">.</span>hostView<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token function">remove</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>components<span class="token punctuation">,</span> compRef<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span>testabilityRegistry<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        testabilityRegistry<span class="token punctuation">.</span><span class="token function">unregisterApplication</span><span class="token punctuation">(</span>nativeElement<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">// 加载组件，包括关联视图、监听变更等</span>
    <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">_loadComponent</span><span class="token punctuation">(</span>compRef<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token operator">...</span>
    <span class="token keyword">return</span> compRef<span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在创建根组件的过程中，会关联 DOM 元素视图、添加对状态变更的检测机制。</p>
<p>根组件是一个入口组件，Angular CLI 创建的默认应用只有一个组件<code v-pre>AppComponent</code>，Angular 会在引导过程中把它加载到 DOM 中。</p>
<p>在根组件的创建过程中，通常会根据根组件中引用到的其他组件，触发一系列组件的创建并形成组件树。大多数应用只有一个组件树，并且只从一个根组件开始引导。</p>
<h3 id="创建组件过程" tabindex="-1"><a class="header-anchor" href="#创建组件过程" aria-hidden="true">#</a> 创建组件过程</h3>
<p>Angular 中创建组件的过程如下（参考<a href="https://angular.cn/guide/architecture-services" target="_blank" rel="noopener noreferrer">服务与依赖注入简介<ExternalLinkIcon/></a>）：</p>
<ol>
<li>当 Angular 创建组件类的新实例时，它会通过查看该组件类的构造函数，来决定该组件依赖哪些服务或其它依赖项。</li>
<li>当 Angular 发现某个组件依赖某个服务时，它会首先检查是否该注入器中已经有了那个服务的任何现有实例。如果所请求的服务尚不存在，注入器就会使用以前注册的服务提供者来制作一个，并把它加入注入器中，然后把该服务返回给 Angular。</li>
<li>当所有请求的服务已解析并返回时，Angular 可以用这些服务实例为参数，调用该组件的构造函数。</li>
</ol>
<p>Angular 会在执行应用时创建注入器，第一个注入器是根注入器，创建于引导过程中。借助注入器继承机制，可以把全应用级的服务注入到这些组件中。</p>
<p>到这里，Angular 分别完成了根模块、根组件和组件树的引导过程，通过编译器则可以将组件和视图渲染到页面上。</p>
<h2 id="总结" tabindex="-1"><a class="header-anchor" href="#总结" aria-hidden="true">#</a> 总结</h2>
<p>在应用程序的引导过程中，Angular 采取了以下步骤来加载我们的第一个视图：</p>
<ol>
<li>加载<code v-pre>index.html</code>。</li>
<li>加载 Angular、第三方库和应用程序。</li>
<li>加载应用程序入口点<code v-pre>Main.ts</code>。</li>
<li>加载根模块。</li>
<li>加载根组件。</li>
<li>加载模板。</li>
</ol>
<p>本文我们重点从根模块的引导过程开始，介绍了引导 Angular 应用程序、引导根组件、组件的创建等过程。至于组件树的创建和渲染，则可以参考<a href="">编译器</a>相关的内容。</p>
<h3 id="参考" tabindex="-1"><a class="header-anchor" href="#参考" aria-hidden="true">#</a> 参考</h3>
<ul>
<li><a href="https://angular.cn/guide/bootstrapping" target="_blank" rel="noopener noreferrer">通过根模块启动应用<ExternalLinkIcon/></a></li>
<li><a href="https://angular.cn/guide/entry-components" target="_blank" rel="noopener noreferrer">Angular-入口组件<ExternalLinkIcon/></a></li>
<li><a href="https://www.tektutorialshub.com/angular/angular-bootstrapping-application/" target="_blank" rel="noopener noreferrer">Bootstrapping in Angular: How It Works Internally<ExternalLinkIcon/></a></li>
</ul>
</div></template>


