<template><div><p>该系列用于探索一些 Angular 中灵活或者新的用法。本文紧跟上节 radio 和 checkbox 表单控件的创建，讲述图片上传表单控件的创建过程。</p>
<!--more-->
<h2 id="图片上传控件的制作" tabindex="-1"><a class="header-anchor" href="#图片上传控件的制作" aria-hidden="true">#</a> 图片上传控件的制作</h2>
<h3 id="type-file-的-input" tabindex="-1"><a class="header-anchor" href="#type-file-的-input" aria-hidden="true">#</a> type=&quot;file&quot;的 input</h3>
<p>要讲图片上传，事情总要从下面的代码开始：</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>input</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>file<span class="token punctuation">"</span></span> <span class="token attr-name">accept</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>image/*<span class="token punctuation">"</span></span> <span class="token attr-name">multiple</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>multiple<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>这里我们允许上传多张，这样的话我们就需要通过数组的方式双向绑定传值。</p>
<p>跟之前的<code v-pre>checkbox-group</code>一样，我们需要自定义<code v-pre>ngModel</code>的绑定过程，这样我们的原型便是：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span>Component<span class="token punctuation">,</span> Input<span class="token punctuation">,</span> OnInit<span class="token punctuation">,</span> ElementRef<span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'@angular/core'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span>customInputAccessor<span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'../../class/custom-input.class'</span><span class="token punctuation">;</span>

@<span class="token function">Component</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">selector</span><span class="token operator">:</span> <span class="token string">'upload-image'</span><span class="token punctuation">,</span>
    <span class="token literal-property property">templateUrl</span><span class="token operator">:</span> <span class="token string">'./upload-image.component.html'</span><span class="token punctuation">,</span>
    <span class="token literal-property property">providers</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token function">customInputAccessor</span><span class="token punctuation">(</span>UploadImageComponent<span class="token punctuation">)</span><span class="token punctuation">]</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">UploadImageComponent</span> <span class="token punctuation">{</span>
    @<span class="token function">Input</span><span class="token punctuation">(</span><span class="token punctuation">)</span> disabled<span class="token operator">:</span> boolean <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>
    @<span class="token function">Input</span><span class="token punctuation">(</span><span class="token punctuation">)</span> required<span class="token operator">:</span> boolean <span class="token operator">=</span> <span class="token boolean">false</span><span class="token punctuation">;</span>

    <span class="token keyword">private</span> <span class="token literal-property property">model</span><span class="token operator">:</span> string<span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token comment">// 控件的值</span>
    <span class="token keyword">private</span> <span class="token function-variable function">onChange</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">_</span><span class="token operator">:</span> any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span>
    <span class="token keyword">private</span> <span class="token function-variable function">onTouched</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token keyword">void</span><span class="token punctuation">;</span>

    <span class="token function">onBlur</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">onTouched</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token function">writeValue</span><span class="token punctuation">(</span>value<span class="token operator">:</span> string<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>value <span class="token operator">&amp;&amp;</span> value<span class="token punctuation">.</span>length<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">this</span><span class="token punctuation">.</span>model <span class="token operator">=</span> value<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>

    <span class="token function">registerOnChange</span><span class="token punctuation">(</span><span class="token function-variable function">fn</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">_</span><span class="token operator">:</span> any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span>onChange <span class="token operator">=</span> fn<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>

    <span class="token function">registerOnTouched</span><span class="token punctuation">(</span><span class="token function-variable function">fn</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span>
        <span class="token keyword">this</span><span class="token punctuation">.</span>onTouched <span class="token operator">=</span> fn<span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如果说这里看不懂，那麻烦大家补一下前两节的内容：
<RouterLink to="/angular/angular-free/7-dynamic-form.html">《7. 创建动态表单》</RouterLink>
<RouterLink to="/angular/angular-free/8-radio-and-checkbox.html">《8. 表单的 radio 和 checkbox》</RouterLink></p>
<h3 id="change-事件" tabindex="-1"><a class="header-anchor" href="#change-事件" aria-hidden="true">#</a> change 事件</h3>
<p>这里我们首先要把原本丑丑的 file input 藏起来，这个通过样式调整就可以啦：</p>
<div class="language-css line-numbers-mode" data-ext="css"><pre v-pre class="language-css"><code><span class="token selector">.btn-file</span> <span class="token punctuation">{</span>
  <span class="token property">position</span><span class="token punctuation">:</span> relative<span class="token punctuation">;</span>
  <span class="token property">overflow</span><span class="token punctuation">:</span> hidden<span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token selector">.btn-file input[type="file"]</span> <span class="token punctuation">{</span>
  <span class="token property">position</span><span class="token punctuation">:</span> absolute<span class="token punctuation">;</span>
  <span class="token property">top</span><span class="token punctuation">:</span> 0<span class="token punctuation">;</span>
  <span class="token property">right</span><span class="token punctuation">:</span> 0<span class="token punctuation">;</span>
  <span class="token property">min-width</span><span class="token punctuation">:</span> 100%<span class="token punctuation">;</span>
  <span class="token property">min-height</span><span class="token punctuation">:</span> 100%<span class="token punctuation">;</span>
  <span class="token property">font-size</span><span class="token punctuation">:</span> 100px<span class="token punctuation">;</span>
  <span class="token property">text-align</span><span class="token punctuation">:</span> right<span class="token punctuation">;</span>
  <span class="token property">filter</span><span class="token punctuation">:</span> <span class="token function">alpha</span><span class="token punctuation">(</span>opacity=0<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token property">opacity</span><span class="token punctuation">:</span> 0<span class="token punctuation">;</span>
  <span class="token property">outline</span><span class="token punctuation">:</span> none<span class="token punctuation">;</span>
  <span class="token property">background</span><span class="token punctuation">:</span> #fff<span class="token punctuation">;</span>
  <span class="token property">cursor</span><span class="token punctuation">:</span> inherit<span class="token punctuation">;</span>
  <span class="token property">display</span><span class="token punctuation">:</span> block<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后我们的 html 调整一下：</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>span</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>btn btn-info btn-file<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>i</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>fa fa-upload fa-fw<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>i</span><span class="token punctuation">></span></span>
  {{btnName}}
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>input</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>file<span class="token punctuation">"</span></span> <span class="token attr-name">accept</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>image/*<span class="token punctuation">"</span></span> <span class="token attr-name">multiple</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>multiple<span class="token punctuation">"</span></span> <span class="token attr-name">(change)</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>upLoad()<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>span</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>是的，我们添加了按钮的名字，这里默认设置为&quot;上传图片就好了&quot;，后面我们再一起看逻辑代码。</p>
<p>这样我们点击呈现的按钮的同时，也就是点击了<code v-pre>&lt;input type=&quot;file&quot; /&gt;</code>，当我们选择了不同的内容之后，<code v-pre>change</code>事件便会触发。</p>
<p>这里我们可以猜想<code v-pre>upload()</code>回调会执行些什么：</p>
<ol>
<li>多个图片，遍历数组。</li>
<li>获取每个图片信息，包括预览 url、名字、大小等等。</li>
</ol>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 拿到input，然后获取选中文件</span>
<span class="token keyword">const</span> input <span class="token operator">=</span> <span class="token function">$</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>el<span class="token punctuation">.</span>nativeElement<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">find</span><span class="token punctuation">(</span><span class="token string">"input"</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> files <span class="token operator">=</span> input<span class="token punctuation">.</span>files<span class="token punctuation">;</span>
<span class="token keyword">if</span> <span class="token punctuation">(</span>files<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token comment">// 遍历文件</span>
  Object<span class="token punctuation">.</span><span class="token function">keys</span><span class="token punctuation">(</span>files<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span><span class="token parameter">index</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token keyword">const</span> file <span class="token operator">=</span> files<span class="token punctuation">[</span>index<span class="token punctuation">]</span><span class="token punctuation">;</span>
    <span class="token comment">// 获取每个图片信息</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="filereader" tabindex="-1"><a class="header-anchor" href="#filereader" aria-hidden="true">#</a> FileReader</h3>
<p>好久没处理上传事件了，我们先来回顾一下<code v-pre>FileReader</code>。</p>
<p><code v-pre>FileReader</code>对象允许 Web 应用程序异步读取存储在用户计算机上的文件（或原始数据缓冲区）的内容，使用<code v-pre>File</code>或<code v-pre>Blob</code>对象指定要读取的文件或数据。</p>
<p>其中<code v-pre>File</code>对象可以是来自用户在一个<code v-pre>&lt;input&gt;</code>元素上选择文件后返回的<code v-pre>FileList</code>对象，也可以来自拖放操作生成的<code v-pre>DataTransfer</code>对象，还可以是来自在一个<code v-pre>HTMLCanvasElement</code>上执行<code v-pre>mozGetAsFile()</code>方法后返回结果。</p>
<ul>
<li>
<p>方法</p>
<ul>
<li><code v-pre>abort()</code>: 中止该读取操作</li>
<li><code v-pre>readAsArrayBuffer(in Blob blob)</code>/<code v-pre>readAsBinaryString(in Blob blob)</code>/<code v-pre>readAsDataURL(in Blob blob)</code>/<code v-pre>readAsText</code>
<ul>
<li>开始读取指定的<code v-pre>Blob</code>对象或<code v-pre>File</code>对象中的内容。当读取操作完成时，<code v-pre>readyState</code>属性的值会成为<code v-pre>DONE</code>，如果设置了<code v-pre>onloadend</code>事件处理程序，则调用</li>
<li>四者区别在于返回的<code v-pre>result</code></li>
<li><code v-pre>readAsDataURL()</code>的<code v-pre>result</code>属性中将包含一个<code v-pre>data: URL</code>格式的字符串以表示所读取文件的内容</li>
</ul>
</li>
</ul>
</li>
<li>
<p>事件处理程序</p>
<ul>
<li><code v-pre>onabort</code>: 当读取操作被中止时调用</li>
<li><code v-pre>onerror</code>: 当读取操作发生错误时调用</li>
<li><code v-pre>onload</code>: 当读取操作成功完成时调用</li>
<li><code v-pre>onloadend</code>: 当读取操作完成时调用,不管是成功还是失败。在 onload 或者 onerror 之后调用</li>
<li><code v-pre>onloadstart</code>: 当读取操作将要开始之前调用</li>
<li><code v-pre>onprogress</code>: 在读取数据过程中周期性调用</li>
</ul>
</li>
</ul>
<p>说这么多，其实我们只需要它的一个<code v-pre>onload</code>事件回调，以及一个<code v-pre>readAsDataURL()</code>方法：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> <span class="token literal-property property">reader</span><span class="token operator">:</span> FileReader <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">FileReader</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">// 设置文件读取完毕事件</span>
reader<span class="token punctuation">.</span><span class="token function-variable function">onload</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">e</span><span class="token operator">:</span> ProgressEvent</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> url <span class="token operator">=</span> reader<span class="token punctuation">.</span>result<span class="token punctuation">;</span> <span class="token comment">// 获取url</span>
  <span class="token keyword">const</span> name <span class="token operator">=</span> file<span class="token punctuation">.</span>name<span class="token punctuation">;</span> <span class="token comment">// 获取文件名字</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
reader<span class="token punctuation">.</span><span class="token function">readAsDataURL</span><span class="token punctuation">(</span>file<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">// 获取图片的data: URL</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="添加校验" tabindex="-1"><a class="header-anchor" href="#添加校验" aria-hidden="true">#</a> 添加校验</h3>
<p>一般来说，我们常用的校验有：大小、宽高、类型。
这里我们使用<code v-pre>limit</code>输入：<code v-pre>@Input() limit: ILimit = {};</code>。</p>
<p>而我们的<code v-pre>limit</code>输入为以下的样子：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">interface</span> <span class="token class-name">ILimit</span> <span class="token punctuation">{</span>
  width<span class="token operator">?</span><span class="token operator">:</span> number<span class="token punctuation">;</span> <span class="token comment">// 宽</span>
  height<span class="token operator">?</span><span class="token operator">:</span> number<span class="token punctuation">;</span> <span class="token comment">// 高</span>
  size<span class="token operator">?</span><span class="token operator">:</span> number<span class="token punctuation">;</span> <span class="token comment">// 大小</span>
  type<span class="token operator">?</span><span class="token operator">:</span> string<span class="token punctuation">;</span> <span class="token comment">// 类型</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>其中我们的大小和类型都可以通过<code v-pre>FileReader</code>获取，那我们的宽高呢？
我们将使用<code v-pre>new Image()</code>来获取。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> image <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Image</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> url <span class="token operator">=</span> reader<span class="token punctuation">.</span>result<span class="token punctuation">;</span>
<span class="token comment">// 添加load事件</span>
image<span class="token punctuation">.</span><span class="token function-variable function">onload</span> <span class="token operator">=</span> <span class="token parameter">ev</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token comment">// image.width</span>
  <span class="token comment">// image.height</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
image<span class="token punctuation">.</span>src <span class="token operator">=</span> url<span class="token punctuation">;</span> <span class="token comment">// 添加图片地址</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="处理错误信息" tabindex="-1"><a class="header-anchor" href="#处理错误信息" aria-hidden="true">#</a> 处理错误信息</h3>
<p>我们的图片校验成功，则进行预览。而校验不通过的话，好的交互则需要我们返回详细的错误信息。
这里我们可以将错误信息收集起来打印：</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">*ngIf</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>checkErrArr.length<span class="token punctuation">"</span></span> <span class="token special-attr"><span class="token attr-name">style</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span><span class="token value css language-css"><span class="token property">color</span><span class="token punctuation">:</span> red<span class="token punctuation">;</span></span><span class="token punctuation">"</span></span></span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">*ngFor</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>let errArr of checkErrArr<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>strong</span><span class="token punctuation">></span></span>{{errArr.name}}<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>strong</span><span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">*ngFor</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>let err of errArr.checkErr<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>{{err}}<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>大家可以看到<code v-pre>checkErrArr</code>将以数组方式存放错误信息。我们添加校验后，<code v-pre>FileReader</code>的 load 事件如下：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> regMap <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token comment">// 图片类型校验</span>
  <span class="token literal-property property">jpg</span><span class="token operator">:</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\.(jpe?g)$</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">,</span>
  <span class="token literal-property property">jpeg</span><span class="token operator">:</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\.(jpe?g)$</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">,</span>
  <span class="token literal-property property">png</span><span class="token operator">:</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\.(png)$</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span><span class="token punctuation">,</span>
  <span class="token literal-property property">gif</span><span class="token operator">:</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\.(gif)$</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
reader<span class="token punctuation">.</span><span class="token function-variable function">onload</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">e</span><span class="token operator">:</span> ProgressEvent</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> image <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Image</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">const</span> url <span class="token operator">=</span> reader<span class="token punctuation">.</span>result<span class="token punctuation">;</span>
  <span class="token keyword">const</span> name <span class="token operator">=</span> file<span class="token punctuation">.</span>name<span class="token punctuation">;</span>
  <span class="token keyword">const</span> checkErr <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  image<span class="token punctuation">.</span><span class="token function-variable function">onload</span> <span class="token operator">=</span> <span class="token parameter">ev</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
    <span class="token comment">// 图片大小校验</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>size <span class="token operator">&amp;&amp;</span> file<span class="token punctuation">.</span>size <span class="token operator">></span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>size <span class="token operator">*</span> <span class="token number">1024</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      checkErr<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token string">"图片大小已超过 "</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>size <span class="token operator">+</span> <span class="token string">" K限制"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token comment">// 图片尺寸校验</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>
      <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>width <span class="token operator">&amp;&amp;</span> image<span class="token punctuation">.</span>width <span class="token operator">></span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>width<span class="token punctuation">)</span> <span class="token operator">||</span>
      <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>height <span class="token operator">&amp;&amp;</span> image<span class="token punctuation">.</span>height <span class="token operator">></span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>height<span class="token punctuation">)</span>
    <span class="token punctuation">)</span> <span class="token punctuation">{</span>
      checkErr<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>
        <span class="token string">"图片尺寸不满足 "</span> <span class="token operator">+</span>
          <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>width <span class="token operator">?</span> <span class="token string">"w: "</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>width <span class="token operator">+</span> <span class="token string">" 以内"</span> <span class="token operator">:</span> <span class="token string">""</span><span class="token punctuation">)</span> <span class="token operator">+</span>
          <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>height <span class="token operator">?</span> <span class="token string">" h: "</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>height <span class="token operator">+</span> <span class="token string">" 以内"</span> <span class="token operator">:</span> <span class="token string">""</span><span class="token punctuation">)</span>
      <span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token comment">// 图片类型校验</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>type <span class="token operator">&amp;&amp;</span>
      regMap<span class="token punctuation">[</span><span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>type<span class="token punctuation">]</span> <span class="token operator">&amp;&amp;</span>
      <span class="token operator">!</span>regMap<span class="token punctuation">[</span><span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>type<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>file<span class="token punctuation">.</span>name<span class="token punctuation">)</span>
    <span class="token punctuation">)</span> <span class="token punctuation">{</span>
      checkErr<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token string">"图片类型不符合要求，需要上传"</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>type<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span>checkErr<span class="token punctuation">.</span>length<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token comment">// 若校验通过，添加进预览列表</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>imagesArr<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span> name<span class="token punctuation">,</span> url <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>model<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>url<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">onChange</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>model<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
      <span class="token comment">// 校验不通过，则收入错误信息</span>
      <span class="token keyword">this</span><span class="token punctuation">.</span>checkErrArr<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token punctuation">{</span> name<span class="token punctuation">,</span> checkErr <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
  image<span class="token punctuation">.</span>src <span class="token operator">=</span> url<span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="添加设置说明" tabindex="-1"><a class="header-anchor" href="#添加设置说明" aria-hidden="true">#</a> 添加设置说明</h3>
<p>这里我们还需要给我们的设定添加说明，像该处做了哪些限制，需要展示出来给用户。
我们通过一个<code v-pre>help</code>字段保存这些协助信息：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>    <span class="token literal-property property">help</span><span class="token operator">:</span> string <span class="token operator">=</span> <span class="token string">''</span><span class="token punctuation">;</span>

    <span class="token function">ngOnInit</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>required<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">this</span><span class="token punctuation">.</span>help <span class="token operator">+=</span> <span class="token string">'必填；'</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>width <span class="token operator">&amp;&amp;</span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>height<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token keyword">this</span><span class="token punctuation">.</span>help <span class="token operator">+=</span> <span class="token string">'图片尺寸：'</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>width <span class="token operator">+</span> <span class="token string">'*'</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>height <span class="token operator">+</span> <span class="token string">'以内'</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>size<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token keyword">this</span><span class="token punctuation">.</span>help <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">.</span>help <span class="token operator">?</span> <span class="token keyword">this</span><span class="token punctuation">.</span>help <span class="token operator">+</span> <span class="token string">','</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>size <span class="token operator">+</span> <span class="token string">'k以内'</span> <span class="token operator">:</span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>size <span class="token operator">+</span> <span class="token string">'k以内'</span><span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>type<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token keyword">this</span><span class="token punctuation">.</span>help <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">.</span>help <span class="token operator">?</span> <span class="token keyword">this</span><span class="token punctuation">.</span>help <span class="token operator">+</span> <span class="token string">',图片类型:'</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>type <span class="token operator">:</span> <span class="token string">',图片类型:'</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>limit<span class="token punctuation">.</span>type<span class="token punctuation">;</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后我们在按钮下面进行辅助说明：</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">*ngIf</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>help<span class="token punctuation">"</span></span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>help-block<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>{{help}}<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="使用-ngmodel-绑定" tabindex="-1"><a class="header-anchor" href="#使用-ngmodel-绑定" aria-hidden="true">#</a> 使用[(ngModel)]绑定</h3>
<p>经过前面的处理，我们的图片上传控件基本完成了。使用方式也很简单，绑定<code v-pre>[(ngModel)]</code>就好了：</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>upload-image</span>
  <span class="token attr-name">[limit]</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>{width:750,height:422,size:30,type:'jpg'}<span class="token punctuation">"</span></span>
  <span class="token attr-name">[(ngModel)]</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>imageArr<span class="token punctuation">"</span></span>
  <span class="token attr-name">[required]</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>true<span class="token punctuation">"</span></span>
<span class="token punctuation">></span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>upload-image</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这里本骚年还传入了些设定，最终效果图如下：</p>
<p><img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/1496243776(1).png" alt="image"></p>
<h2 id="结束语" tabindex="-1"><a class="header-anchor" href="#结束语" aria-hidden="true">#</a> 结束语</h2>
<p>上传图片控件和前面动态表单的结合大家可以自行实践，本骚年也将实现代码放到项目里了。<br>
不知道是不是 FileReader 的原因，上传文件变得好慢，或许是本骚年的使用方式不对。不知道大家有啥建议没呢？<br>
<a href="https://github.com/godbasin/godbasin.github.io/tree/blog-codes/angular2-free/9-upload-iamge" target="_blank" rel="noopener noreferrer">此处查看项目代码<ExternalLinkIcon/></a><br>
<a href="http://angular2-free.godbasin.com/9-upload-iamge/index.html#/home/page-setting" target="_blank" rel="noopener noreferrer">此处查看页面效果<ExternalLinkIcon/></a></p>
</div></template>


