<template><div><p>第五章主要介绍操作(operation)。</p>
<!--more-->
<h2 id="鼠标获取刚体" tabindex="-1"><a class="header-anchor" href="#鼠标获取刚体" aria-hidden="true">#</a> 鼠标获取刚体</h2>
<h3 id="鼠标获取刚体-对刚体进行操作的前提" tabindex="-1"><a class="header-anchor" href="#鼠标获取刚体-对刚体进行操作的前提" aria-hidden="true">#</a> 鼠标获取刚体--对刚体进行操作的前提</h3>
<p>Box2D 中，只要提供一个 AABB 的坐标，b2World 就可以返回一个数组，用于保存所有相交于此 AABB 的形状。</p>
<p>所以，为了利用鼠标获取刚体，首先要画出一个小区域，这个区域小到近似于一个点，然后遍历整个世界的形状，判断鼠标点击位置所画出的小区域是否与某个形状重合，如果有重合，再由这个形状得到这个形状所属的刚体。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">GetBodyAtMouse</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token comment">//首先创建一个近似于点的小区域</span>
  <span class="token keyword">var</span> mousePVec <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span>mousedwX<span class="token punctuation">,</span> mousedwY<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">//利用b2Vec2定义一个矢量，用来保存鼠标点击的点</span>
  <span class="token keyword">var</span> aabb <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2AABB</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">//利用b2AABB创建一个环境</span>
  aabb<span class="token punctuation">.</span>minVertex<span class="token punctuation">.</span><span class="token function">Set</span><span class="token punctuation">(</span>mousePVec<span class="token punctuation">.</span>x <span class="token operator">-</span> <span class="token number">0.001</span><span class="token punctuation">,</span> mousePVec<span class="token punctuation">.</span>y <span class="token operator">-</span> <span class="token number">0.001</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  aabb<span class="token punctuation">.</span>maxVertex<span class="token punctuation">.</span><span class="token function">Set</span><span class="token punctuation">(</span>mousePVec<span class="token punctuation">.</span>x <span class="token operator">+</span> <span class="token number">0.001</span><span class="token punctuation">,</span> mousePVec<span class="token punctuation">.</span>y <span class="token operator">+</span> <span class="token number">0.001</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token comment">//设置aabb的左上角及右下角坐标，这里是以鼠标点击位置为中心创建了一个长、宽均为0.002的矩形区域</span>

  <span class="token comment">//然后查询与指定区域有重叠的刚体</span>
  <span class="token keyword">var</span> k_maxCount <span class="token operator">=</span> <span class="token number">10</span><span class="token punctuation">;</span> <span class="token comment">//设定所要查找形状的数量，注意合理设置其大小，过大会影响运行速度</span>
  <span class="token keyword">var</span> shapes <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Array</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//保存查找到的与已知边界盒相交的形状</span>
  <span class="token keyword">var</span> count <span class="token operator">=</span> world<span class="token punctuation">.</span><span class="token function">Query</span><span class="token punctuation">(</span>aabb<span class="token punctuation">,</span> shapes<span class="token punctuation">,</span> k_maxCount<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//在世界中查找与边界盒相交的maxCount个形状，并返回边界盒区域内实际包含的形状的个数</span>

  <span class="token keyword">var</span> findBody <span class="token operator">=</span> <span class="token keyword">null</span><span class="token punctuation">;</span> <span class="token comment">//首先设定没有找到物体</span>
  <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> count<span class="token punctuation">;</span> <span class="token operator">++</span>i<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>shapes<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">GetBody</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">IsStatic</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token boolean">false</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token comment">//条件假定查找到的形状不是静态刚体，比如墙</span>
      <span class="token keyword">var</span> tShape <span class="token operator">=</span> shapes<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">;</span> <span class="token comment">//将查找到的形状赋给tShape变量</span>
      <span class="token keyword">var</span> inside <span class="token operator">=</span> tShape<span class="token punctuation">.</span><span class="token function">GetBody</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//将tShape对应的刚体赋给inside</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span>inside<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">//如果inside这个刚体存在</span>
        <span class="token comment">//那么返回这个刚体，并跳出遍历</span>
        findBody <span class="token operator">=</span> tShape<span class="token punctuation">.</span><span class="token function">GetBody</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">break</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
  <span class="token keyword">return</span> findBody<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="获取参与碰撞的刚体" tabindex="-1"><a class="header-anchor" href="#获取参与碰撞的刚体" aria-hidden="true">#</a> 获取参与碰撞的刚体</h2>
<h3 id="m-contactlist" tabindex="-1"><a class="header-anchor" href="#m-contactlist" aria-hidden="true">#</a> m_contactList</h3>
<p>m_contactList 的类型是 b2ContactNode，取得附加在该物体上的碰撞表，所有碰撞都保存在这个列表里。
同 ShapeList 相比，ShapeList 保存的是世界中所有的形状，而 contactlist 保存的是参与碰撞的形状。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">getContactInf</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">for</span> <span class="token punctuation">(</span>
    <span class="token keyword">var</span> b <span class="token operator">=</span> world<span class="token punctuation">.</span>m_contactList<span class="token punctuation">;</span>
    b<span class="token punctuation">;</span>
    b <span class="token operator">=</span> b<span class="token punctuation">.</span>m_next <span class="token comment">// 遍历contactlist所有世界，直到b不存在，跳出循环</span>
  <span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// 将b里的两个刚体分别定义为b1和b2</span>
    <span class="token keyword">var</span> b1 <span class="token operator">=</span> b<span class="token punctuation">.</span>m_shape1<span class="token punctuation">.</span>m_body<span class="token punctuation">;</span>
    <span class="token keyword">var</span> b2 <span class="token operator">=</span> b<span class="token punctuation">.</span>m_shape2<span class="token punctuation">.</span>m_body<span class="token punctuation">;</span>

    <span class="token comment">// 向下执行的条件是b1和b2不同，且不是三面挡板（BodyTop/BodyLeft/BodyRight）</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>
      b1 <span class="token operator">!=</span> Body2 <span class="token operator">&amp;&amp;</span>
      b1 <span class="token operator">!=</span> BodyTop <span class="token operator">&amp;&amp;</span>
      b1 <span class="token operator">!=</span> BodyLeft <span class="token operator">&amp;&amp;</span>
      b1 <span class="token operator">!=</span> BodyRight <span class="token operator">&amp;&amp;</span>
      b2 <span class="token operator">!=</span> Body2 <span class="token operator">&amp;&amp;</span>
      b2 <span class="token operator">!=</span> BodyTop <span class="token operator">&amp;&amp;</span>
      b2 <span class="token operator">!=</span> BodyLeft <span class="token operator">&amp;&amp;</span>
      b2 <span class="token operator">!=</span> BodyRight
    <span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token punctuation">}</span>
    <span class="token comment">// 备注：得到了参与碰撞的刚体，则可以对其中的所有刚体的操作，这个发挥的空间留给游戏开发过程</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="getcontactlist" tabindex="-1"><a class="header-anchor" href="#getcontactlist" aria-hidden="true">#</a> GetContactList</h3>
<p>GetContactList 其实与上面的作用效果一样，而且其判断接触的逻辑思路也是一致的。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> cn <span class="token operator">=</span> world<span class="token punctuation">.</span><span class="token function">GetContactList</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> cn <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">;</span> cn <span class="token operator">=</span> cn<span class="token punctuation">.</span><span class="token function">GetNext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">var</span> body1 <span class="token operator">=</span> cn<span class="token punctuation">.</span><span class="token function">GetShape1</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">GetBody</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> body2 <span class="token operator">=</span> cn<span class="token punctuation">.</span><span class="token function">GetShape2</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">GetBody</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token comment">// 处理判断发生碰撞的两个刚体是不是分别为箱子和墙壁</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token punctuation">(</span>body1 <span class="token operator">==</span> box <span class="token operator">&amp;&amp;</span> body2 <span class="token operator">==</span> wall<span class="token punctuation">)</span> <span class="token operator">||</span> <span class="token punctuation">(</span>body2 <span class="token operator">==</span> box <span class="token operator">&amp;&amp;</span> body1 <span class="token operator">==</span> wall<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// 进行逻辑处理</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="获取刚体的各属性" tabindex="-1"><a class="header-anchor" href="#获取刚体的各属性" aria-hidden="true">#</a> 获取刚体的各属性</h2>
<h3 id="body-get属性名" tabindex="-1"><a class="header-anchor" href="#body-get属性名" aria-hidden="true">#</a> <code v-pre>Body.Get属性名()</code></h3>
<p>在实际编程中，往往需要得到一些关于刚体的信息、数据等，以便下一步对刚体进行一系列操作。
下面代码中给出了获取某些数据的方法，还有一些设置刚体属性的语句。语法格式一般为 Body.Get 属性名()。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">showAllFuc</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token comment">//获得刚体位置</span>
  <span class="token keyword">var</span> OriginPosition <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//利用b2Vec2定义一个起始位置的二维矢量</span>
  OriginPosition <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">GetOriginPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//获取刚体坐标原点，对称图形的原点即中心点</span>
  <span class="token function">alert</span><span class="token punctuation">(</span>OriginPosition<span class="token punctuation">.</span>x <span class="token operator">+</span> <span class="token string">","</span> <span class="token operator">+</span> OriginPosition<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//显示该坐标</span>

  <span class="token keyword">var</span> mass<span class="token punctuation">;</span>
  mass <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">GetMass</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//获取刚体质量</span>

  <span class="token keyword">var</span> inertia<span class="token punctuation">;</span>
  inertia <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">GetInertia</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//获取惯性，类似力的大小</span>
  <span class="token function">alert</span><span class="token punctuation">(</span>inertia<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">var</span> worldPoint<span class="token punctuation">;</span>
  <span class="token keyword">var</span> localPoint <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span><span class="token number">100</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  worldPoint <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">GetWorldPoint</span><span class="token punctuation">(</span>localPoint<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//由局部坐标得到世界坐标</span>
  <span class="token function">alert</span><span class="token punctuation">(</span>
    slectBody<span class="token punctuation">.</span><span class="token function">GetCenterPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>x <span class="token operator">+</span> <span class="token string">","</span> <span class="token operator">+</span> slectBody<span class="token punctuation">.</span><span class="token function">GetCenterPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>y
  <span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//世界坐标=局部坐标+刚体中心点坐标</span>
  <span class="token function">alert</span><span class="token punctuation">(</span>localPoint<span class="token punctuation">.</span>x <span class="token operator">+</span> <span class="token string">","</span> <span class="token operator">+</span> localPoint<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token function">alert</span><span class="token punctuation">(</span>worldPoint<span class="token punctuation">.</span>x <span class="token operator">+</span> <span class="token string">","</span> <span class="token operator">+</span> worldPoint<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">var</span> localVector<span class="token punctuation">;</span>
  <span class="token keyword">var</span> worldVector <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span>
    slectBody<span class="token punctuation">.</span><span class="token function">GetCenterPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>x<span class="token punctuation">,</span>
    slectBody<span class="token punctuation">.</span><span class="token function">GetCenterPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>y
  <span class="token punctuation">)</span><span class="token punctuation">;</span>
  localVector <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">GetLocalVector</span><span class="token punctuation">(</span>worldVector<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token function">alert</span><span class="token punctuation">(</span>worldVector<span class="token punctuation">.</span>x <span class="token operator">+</span> <span class="token string">","</span> <span class="token operator">+</span> worldVector<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token function">alert</span><span class="token punctuation">(</span>localVector<span class="token punctuation">.</span>x <span class="token operator">+</span> <span class="token string">","</span> <span class="token operator">+</span> localVector<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">var</span> staticFlage<span class="token punctuation">;</span> <span class="token comment">//定义一个静态标志</span>
  staticFlage <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">IsStatic</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//判断选中物体是否为静止不可移动的刚体，并将结果反馈给静态标志</span>
  <span class="token function">alert</span><span class="token punctuation">(</span>staticFlage<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">var</span> frozenFlage<span class="token punctuation">;</span>
  frozenFlage <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">IsFrozen</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token function">alert</span><span class="token punctuation">(</span>frozenFlage<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">var</span> sleepingFlage<span class="token punctuation">;</span> <span class="token comment">//定义一个睡眠标志</span>
  sleepingFlage <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">IsSleeping</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//判断选中物体是否已进入睡眠状态，并将结果反 馈给静态标志</span>
  <span class="token function">alert</span><span class="token punctuation">(</span>sleepingFlage<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">var</span> allowSleepingFlage <span class="token operator">=</span> <span class="token number">1</span><span class="token punctuation">;</span> <span class="token comment">//定义一个允许睡眠的标志，并设定初值为1，即允许睡眠</span>
  slectBody<span class="token punctuation">.</span><span class="token function">AllowSleeping</span><span class="token punctuation">(</span>allowSleepingFlage<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//根据标志判断是否允许睡眠，是则可进入睡眠状态，否则唤醒</span>
  slectBody<span class="token punctuation">.</span><span class="token function">WakeUp</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//唤醒睡眠刚体，对于非静止刚体，只有碰撞才能自动唤醒，对其赋予速度、力等值时，需要先行唤醒才有效果</span>

  <span class="token keyword">var</span> shapeList <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Array</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  shapeList <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">GetShapeList</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//数组内保存选中刚体的shapelist；直接用m_shapeList效果一样,列表里是一个个的shape，shape是一个类，其表面形状类型的属性为shape.m_type</span>
  slectBody<span class="token punctuation">.</span><span class="token function">Destroy</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//在世界里销毁该刚体</span>
  slectBody<span class="token punctuation">.</span><span class="token function">GetNext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//获取下一刚体，在world里刚体储存在m_BodyList里</span>

  <span class="token keyword">var</span> otherBody <span class="token operator">=</span> Body4<span class="token punctuation">;</span>
  <span class="token keyword">var</span> conectJuge<span class="token punctuation">;</span>
  conectJuge <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">IsConnected</span><span class="token punctuation">(</span>otherBody<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//判定选定的刚体是否与另一刚体相连，相连则不碰撞</span>
  <span class="token function">alert</span><span class="token punctuation">(</span>conectJuge<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="为刚体设置属性" tabindex="-1"><a class="header-anchor" href="#为刚体设置属性" aria-hidden="true">#</a> 为刚体设置属性</h2>
<h3 id="设置刚体的属性" tabindex="-1"><a class="header-anchor" href="#设置刚体的属性" aria-hidden="true">#</a> 设置刚体的属性</h3>
<p>创建一个刚体之后，还可以对它进行许多操作，比如设置质量，访问其位置和速度，施加力，以及转换点和向量等。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 设置刚体的属性</span>
<span class="token keyword">var</span> position <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span><span class="token number">200</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//定义一个点坐标（200，100）</span>
<span class="token keyword">var</span> rotation <span class="token operator">=</span> <span class="token number">0.3</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span><span class="token punctuation">;</span> <span class="token comment">//定义一个弧度值</span>
spclBodyDef<span class="token punctuation">.</span>position<span class="token punctuation">.</span><span class="token function">Set</span><span class="token punctuation">(</span>basicX<span class="token punctuation">,</span> basicY<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//设置物体的初始位置置，括号内是矢量坐标</span>
slectBody<span class="token punctuation">.</span><span class="token function">SetCenterPosition</span><span class="token punctuation">(</span>position<span class="token punctuation">,</span> rotation<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//设置选中的刚体的中心位置及其旋转弧度</span>

<span class="token keyword">var</span> CenterPosition <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
CenterPosition <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">GetCenterPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token function">alert</span><span class="token punctuation">(</span>CenterPosition<span class="token punctuation">.</span>x <span class="token operator">+</span> <span class="token string">","</span> <span class="token operator">+</span> CenterPosition<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> RotationMatrix <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Mat22</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
RotationMatrix <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">GetRotationMatrix</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//获取一个2X2的刚体旋转矩阵</span>
<span class="token function">alert</span><span class="token punctuation">(</span>RotationMatrix<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> LinearVelocity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span><span class="token number">500</span><span class="token punctuation">,</span> <span class="token operator">-</span><span class="token number">500</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//定义一个线速度</span>
slectBody<span class="token punctuation">.</span><span class="token function">WakeUp</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//唤醒选中物体，刷新数据</span>
slectBody<span class="token punctuation">.</span><span class="token function">SetLinearVelocity</span><span class="token punctuation">(</span>LinearVelocity<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//设定选中物体的线速度</span>

<span class="token keyword">var</span> LinearVelocity <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
LinearVelocity <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">GetLinearVelocity</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//获取选中刚体的线速度向量</span>
<span class="token function">alert</span><span class="token punctuation">(</span>LinearVelocity<span class="token punctuation">.</span>x <span class="token operator">+</span> <span class="token string">","</span> <span class="token operator">+</span> LinearVelocity<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> AngularVelocity <span class="token operator">=</span> <span class="token number">100</span><span class="token punctuation">;</span> <span class="token comment">//定义一个角速度</span>
slectBody<span class="token punctuation">.</span><span class="token function">WakeUp</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
slectBody<span class="token punctuation">.</span><span class="token function">SetAngularVelocity</span><span class="token punctuation">(</span>AngularVelocity<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//设定选中物体的角速度</span>

<span class="token keyword">var</span> AngularVelocity<span class="token punctuation">;</span>
AngularVelocity <span class="token operator">=</span> slectBody<span class="token punctuation">.</span><span class="token function">GetAngularVelocity</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//获取选中刚体的角速度向量</span>
<span class="token function">alert</span><span class="token punctuation">(</span>AngularVelocity<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> force <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span><span class="token number">10000</span><span class="token punctuation">,</span> <span class="token number">1000000000</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//定义一个力的大小及方向</span>
<span class="token keyword">var</span> point <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span>
  slectBody<span class="token punctuation">.</span><span class="token function">GetCenterPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>x<span class="token punctuation">,</span>
  slectBody<span class="token punctuation">.</span><span class="token function">GetCenterPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>y
<span class="token punctuation">)</span><span class="token punctuation">;</span>
slectBody<span class="token punctuation">.</span><span class="token function">WakeUp</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//在指定点给物体施加一个已知大小与方向的力</span>
<span class="token comment">//施加一个力,需要很大才有效果，不如直接给定线速度，一般给力据F=ma给定</span>
slectBody<span class="token punctuation">.</span><span class="token function">ApplyForce</span><span class="token punctuation">(</span>force<span class="token punctuation">,</span> point<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token function">alert</span><span class="token punctuation">(</span>slectBody<span class="token punctuation">.</span>m_linearVelocity<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">var</span> torque <span class="token operator">=</span> <span class="token number">100000000000</span><span class="token punctuation">;</span> <span class="token comment">//定义一个力矩</span>
slectBody<span class="token punctuation">.</span><span class="token function">WakeUp</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
slectBody<span class="token punctuation">.</span><span class="token function">ApplyTorque</span><span class="token punctuation">(</span>torque<span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//设定选定物体的力矩，数值较大，可以通过设定角速度大小实现相同功能</span>

<span class="token keyword">var</span> impulse <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">100000000</span><span class="token punctuation">)</span><span class="token punctuation">;</span> <span class="token comment">//定义一个物体的冲量</span>
<span class="token keyword">var</span> point <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span>
  slectBody<span class="token punctuation">.</span><span class="token function">GetCenterPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>x<span class="token punctuation">,</span>
  slectBody<span class="token punctuation">.</span><span class="token function">GetCenterPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>y
<span class="token punctuation">)</span><span class="token punctuation">;</span>
slectBody<span class="token punctuation">.</span><span class="token function">WakeUp</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token comment">//在指定点给物体施加一个已知大小与方向的冲量，一般在初始的时候给定，以便决定初始运动</span>
slectBody<span class="token punctuation">.</span><span class="token function">ApplyImpulse</span><span class="token punctuation">(</span>impulse<span class="token punctuation">,</span> point<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="绘制刚体" tabindex="-1"><a class="header-anchor" href="#绘制刚体" aria-hidden="true">#</a> 绘制刚体</h2>
<hr>
<h3 id="绘制刚体图片" tabindex="-1"><a class="header-anchor" href="#绘制刚体图片" aria-hidden="true">#</a> 绘制刚体图片</h3>
<ol>
<li>在页面中加入图片，并捆绑 id</li>
</ol>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>img</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>box<span class="token punctuation">"</span></span> <span class="token attr-name">src</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>images/box.png<span class="token punctuation">"</span></span> <span class="token punctuation">/></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><ol start="2">
<li>设置形状定义的 userData 为图片 id</li>
</ol>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>boxSd<span class="token punctuation">.</span>userData <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">getElementById</span><span class="token punctuation">(</span><span class="token string">"box"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><ol start="3">
<li>在绘制世界时，将图片信息绘制进去</li>
</ol>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 绘画世界</span>
<span class="token keyword">function</span> <span class="token function">drawWorld</span><span class="token punctuation">(</span><span class="token parameter">world<span class="token punctuation">,</span> context</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> b <span class="token operator">=</span> world<span class="token punctuation">.</span>m_bodyList<span class="token punctuation">;</span> b <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">;</span> b <span class="token operator">=</span> b<span class="token punctuation">.</span>m_next<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> s <span class="token operator">=</span> b<span class="token punctuation">.</span><span class="token function">GetShapeList</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> s <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">;</span> s <span class="token operator">=</span> s<span class="token punctuation">.</span><span class="token function">GetNext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span>s<span class="token punctuation">.</span><span class="token function">GetUserData</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">!=</span> <span class="token keyword">undefined</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// 使用数据包括图片</span>
        <span class="token keyword">var</span> img <span class="token operator">=</span> s<span class="token punctuation">.</span><span class="token function">GetUserData</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

        <span class="token comment">// 图片的长和宽</span>
        <span class="token keyword">var</span> x <span class="token operator">=</span> s<span class="token punctuation">.</span><span class="token function">GetPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>x<span class="token punctuation">;</span>
        <span class="token keyword">var</span> y <span class="token operator">=</span> s<span class="token punctuation">.</span><span class="token function">GetPosition</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>y<span class="token punctuation">;</span>
        <span class="token keyword">var</span> topleftX <span class="token operator">=</span> <span class="token operator">-</span><span class="token function">$</span><span class="token punctuation">(</span>img<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">width</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">;</span>
        <span class="token keyword">var</span> topleftY <span class="token operator">=</span> <span class="token operator">-</span><span class="token function">$</span><span class="token punctuation">(</span>img<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">height</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">/</span> <span class="token number">2</span><span class="token punctuation">;</span>

        context<span class="token punctuation">.</span><span class="token function">save</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        context<span class="token punctuation">.</span><span class="token function">translate</span><span class="token punctuation">(</span>x<span class="token punctuation">,</span> y<span class="token punctuation">)</span><span class="token punctuation">;</span>
        context<span class="token punctuation">.</span><span class="token function">rotate</span><span class="token punctuation">(</span>s<span class="token punctuation">.</span><span class="token function">GetBody</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">GetRotation</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        context<span class="token punctuation">.</span><span class="token function">drawImage</span><span class="token punctuation">(</span>img<span class="token punctuation">,</span> topleftX<span class="token punctuation">,</span> topleftY<span class="token punctuation">)</span><span class="token punctuation">;</span>
        context<span class="token punctuation">.</span><span class="token function">restore</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
      <span class="token function">drawShape</span><span class="token punctuation">(</span>s<span class="token punctuation">,</span> context<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>注意，以上的方法只试用于圆形和矩形，多边形待验证。</p>
<h3 id="绘制刚体形状" tabindex="-1"><a class="header-anchor" href="#绘制刚体形状" aria-hidden="true">#</a> 绘制刚体形状</h3>
<p>有时候我们需要将刚体和关节的形状绘制出来：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 从draw_world.js里面引用的绘画功能</span>
<span class="token keyword">function</span> <span class="token function">drawShape</span><span class="token punctuation">(</span><span class="token parameter">shape<span class="token punctuation">,</span> context</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  context<span class="token punctuation">.</span>strokeStyle <span class="token operator">=</span> <span class="token string">"#003300"</span><span class="token punctuation">;</span>
  context<span class="token punctuation">.</span><span class="token function">beginPath</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">switch</span> <span class="token punctuation">(</span>shape<span class="token punctuation">.</span>m_type<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// 绘制圆</span>
    <span class="token keyword">case</span> b2Shape<span class="token punctuation">.</span>e_circleShape<span class="token operator">:</span>
      <span class="token keyword">var</span> circle <span class="token operator">=</span> shape<span class="token punctuation">;</span>
      <span class="token keyword">var</span> pos <span class="token operator">=</span> circle<span class="token punctuation">.</span>m_position<span class="token punctuation">;</span>
      <span class="token keyword">var</span> r <span class="token operator">=</span> circle<span class="token punctuation">.</span>m_radius<span class="token punctuation">;</span>
      <span class="token keyword">var</span> segments <span class="token operator">=</span> <span class="token number">16.0</span><span class="token punctuation">;</span>
      <span class="token keyword">var</span> theta <span class="token operator">=</span> <span class="token number">0.0</span><span class="token punctuation">;</span>
      <span class="token keyword">var</span> dtheta <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token number">2.0</span> <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token constant">PI</span><span class="token punctuation">)</span> <span class="token operator">/</span> segments<span class="token punctuation">;</span>
      <span class="token comment">// 画圆圈</span>
      context<span class="token punctuation">.</span><span class="token function">moveTo</span><span class="token punctuation">(</span>pos<span class="token punctuation">.</span>x <span class="token operator">+</span> r<span class="token punctuation">,</span> pos<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> segments<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">var</span> d <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span>r <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token function">cos</span><span class="token punctuation">(</span>theta<span class="token punctuation">)</span><span class="token punctuation">,</span> r <span class="token operator">*</span> Math<span class="token punctuation">.</span><span class="token function">sin</span><span class="token punctuation">(</span>theta<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">var</span> v <span class="token operator">=</span> b2Math<span class="token punctuation">.</span><span class="token function">AddVV</span><span class="token punctuation">(</span>pos<span class="token punctuation">,</span> d<span class="token punctuation">)</span><span class="token punctuation">;</span>
        context<span class="token punctuation">.</span><span class="token function">lineTo</span><span class="token punctuation">(</span>v<span class="token punctuation">.</span>x<span class="token punctuation">,</span> v<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
        theta <span class="token operator">+=</span> dtheta<span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
      context<span class="token punctuation">.</span><span class="token function">lineTo</span><span class="token punctuation">(</span>pos<span class="token punctuation">.</span>x <span class="token operator">+</span> r<span class="token punctuation">,</span> pos<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>

      <span class="token comment">// 画半径</span>
      context<span class="token punctuation">.</span><span class="token function">moveTo</span><span class="token punctuation">(</span>pos<span class="token punctuation">.</span>x<span class="token punctuation">,</span> pos<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">var</span> ax <span class="token operator">=</span> circle<span class="token punctuation">.</span>m_R<span class="token punctuation">.</span>col1<span class="token punctuation">;</span>
      <span class="token keyword">var</span> pos2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">b2Vec2</span><span class="token punctuation">(</span>pos<span class="token punctuation">.</span>x <span class="token operator">+</span> r <span class="token operator">*</span> ax<span class="token punctuation">.</span>x<span class="token punctuation">,</span> pos<span class="token punctuation">.</span>y <span class="token operator">+</span> r <span class="token operator">*</span> ax<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      context<span class="token punctuation">.</span><span class="token function">lineTo</span><span class="token punctuation">(</span>pos2<span class="token punctuation">.</span>x<span class="token punctuation">,</span> pos2<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">break</span><span class="token punctuation">;</span>
    <span class="token comment">// 绘制多边形</span>
    <span class="token keyword">case</span> b2Shape<span class="token punctuation">.</span>e_polyShape<span class="token operator">:</span>
      <span class="token keyword">var</span> poly <span class="token operator">=</span> shape<span class="token punctuation">;</span>
      <span class="token keyword">var</span> tV <span class="token operator">=</span> b2Math<span class="token punctuation">.</span><span class="token function">AddVV</span><span class="token punctuation">(</span>
        poly<span class="token punctuation">.</span>m_position<span class="token punctuation">,</span>
        b2Math<span class="token punctuation">.</span><span class="token function">b2MulMV</span><span class="token punctuation">(</span>poly<span class="token punctuation">.</span>m_R<span class="token punctuation">,</span> poly<span class="token punctuation">.</span>m_vertices<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
      <span class="token punctuation">)</span><span class="token punctuation">;</span>
      context<span class="token punctuation">.</span><span class="token function">moveTo</span><span class="token punctuation">(</span>tV<span class="token punctuation">.</span>x<span class="token punctuation">,</span> tV<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> poly<span class="token punctuation">.</span>m_vertexCount<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">var</span> v <span class="token operator">=</span> b2Math<span class="token punctuation">.</span><span class="token function">AddVV</span><span class="token punctuation">(</span>
          poly<span class="token punctuation">.</span>m_position<span class="token punctuation">,</span>
          b2Math<span class="token punctuation">.</span><span class="token function">b2MulMV</span><span class="token punctuation">(</span>poly<span class="token punctuation">.</span>m_R<span class="token punctuation">,</span> poly<span class="token punctuation">.</span>m_vertices<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">)</span>
        <span class="token punctuation">)</span><span class="token punctuation">;</span>
        context<span class="token punctuation">.</span><span class="token function">lineTo</span><span class="token punctuation">(</span>v<span class="token punctuation">.</span>x<span class="token punctuation">,</span> v<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
      context<span class="token punctuation">.</span><span class="token function">lineTo</span><span class="token punctuation">(</span>tV<span class="token punctuation">.</span>x<span class="token punctuation">,</span> tV<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">break</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  context<span class="token punctuation">.</span><span class="token function">stroke</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="绘制关节" tabindex="-1"><a class="header-anchor" href="#绘制关节" aria-hidden="true">#</a> 绘制关节</h2>
<h3 id="绘制关节-1" tabindex="-1"><a class="header-anchor" href="#绘制关节-1" aria-hidden="true">#</a> 绘制关节</h3>
<ul>
<li>在绘制世界时加入关节的判断和绘制调用</li>
</ul>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">drawWorld</span><span class="token punctuation">(</span><span class="token parameter">world<span class="token punctuation">,</span> context</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> j <span class="token operator">=</span> world<span class="token punctuation">.</span>m_jointList<span class="token punctuation">;</span> j<span class="token punctuation">;</span> j <span class="token operator">=</span> j<span class="token punctuation">.</span>m_next<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// 绘制关节</span>
    <span class="token function">drawJoint</span><span class="token punctuation">(</span>j<span class="token punctuation">,</span> context<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> b <span class="token operator">=</span> world<span class="token punctuation">.</span>m_bodyList<span class="token punctuation">;</span> b<span class="token punctuation">;</span> b <span class="token operator">=</span> b<span class="token punctuation">.</span>m_next<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> s <span class="token operator">=</span> b<span class="token punctuation">.</span><span class="token function">GetShapeList</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span> s <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">;</span> s <span class="token operator">=</span> s<span class="token punctuation">.</span><span class="token function">GetNext</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token comment">// 绘制刚体形状</span>
      <span class="token function">drawShape</span><span class="token punctuation">(</span>s<span class="token punctuation">,</span> context<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><ul>
<li>绘制关节</li>
</ul>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">function</span> <span class="token function">drawJoint</span><span class="token punctuation">(</span><span class="token parameter">joint<span class="token punctuation">,</span> context</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">var</span> b1 <span class="token operator">=</span> joint<span class="token punctuation">.</span>m_body1<span class="token punctuation">;</span>
  <span class="token keyword">var</span> b2 <span class="token operator">=</span> joint<span class="token punctuation">.</span>m_body2<span class="token punctuation">;</span>
  <span class="token keyword">var</span> x1 <span class="token operator">=</span> b1<span class="token punctuation">.</span>m_position<span class="token punctuation">;</span>
  <span class="token keyword">var</span> x2 <span class="token operator">=</span> b2<span class="token punctuation">.</span>m_position<span class="token punctuation">;</span>
  <span class="token keyword">var</span> p1 <span class="token operator">=</span> joint<span class="token punctuation">.</span><span class="token function">GetAnchor1</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">var</span> p2 <span class="token operator">=</span> joint<span class="token punctuation">.</span><span class="token function">GetAnchor2</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  context<span class="token punctuation">.</span>strokeStyle <span class="token operator">=</span> <span class="token string">"#00eeee"</span><span class="token punctuation">;</span>
  context<span class="token punctuation">.</span><span class="token function">beginPath</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">switch</span> <span class="token punctuation">(</span>joint<span class="token punctuation">.</span>m_type<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// 绘制距离关节</span>
    <span class="token keyword">case</span> b2Joint<span class="token punctuation">.</span>e_distanceJoint<span class="token operator">:</span>
      context<span class="token punctuation">.</span><span class="token function">moveTo</span><span class="token punctuation">(</span>p1<span class="token punctuation">.</span>x<span class="token punctuation">,</span> p1<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      context<span class="token punctuation">.</span><span class="token function">lineTo</span><span class="token punctuation">(</span>p2<span class="token punctuation">.</span>x<span class="token punctuation">,</span> p2<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token keyword">break</span><span class="token punctuation">;</span>

    <span class="token keyword">case</span> b2Joint<span class="token punctuation">.</span>e_pulleyJoint<span class="token operator">:</span>
      <span class="token comment">// TODO</span>
      <span class="token keyword">break</span><span class="token punctuation">;</span>

    <span class="token keyword">default</span><span class="token operator">:</span>
      <span class="token keyword">if</span> <span class="token punctuation">(</span>b1 <span class="token operator">==</span> world<span class="token punctuation">.</span>m_groundBody<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        context<span class="token punctuation">.</span><span class="token function">moveTo</span><span class="token punctuation">(</span>p1<span class="token punctuation">.</span>x<span class="token punctuation">,</span> p1<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
        context<span class="token punctuation">.</span><span class="token function">lineTo</span><span class="token punctuation">(</span>x2<span class="token punctuation">.</span>x<span class="token punctuation">,</span> x2<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>b2 <span class="token operator">==</span> world<span class="token punctuation">.</span>m_groundBody<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        context<span class="token punctuation">.</span><span class="token function">moveTo</span><span class="token punctuation">(</span>p1<span class="token punctuation">.</span>x<span class="token punctuation">,</span> p1<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
        context<span class="token punctuation">.</span><span class="token function">lineTo</span><span class="token punctuation">(</span>x1<span class="token punctuation">.</span>x<span class="token punctuation">,</span> x1<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
        context<span class="token punctuation">.</span><span class="token function">moveTo</span><span class="token punctuation">(</span>x1<span class="token punctuation">.</span>x<span class="token punctuation">,</span> x1<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
        context<span class="token punctuation">.</span><span class="token function">lineTo</span><span class="token punctuation">(</span>p1<span class="token punctuation">.</span>x<span class="token punctuation">,</span> p1<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
        context<span class="token punctuation">.</span><span class="token function">lineTo</span><span class="token punctuation">(</span>x2<span class="token punctuation">.</span>x<span class="token punctuation">,</span> x2<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
        context<span class="token punctuation">.</span><span class="token function">lineTo</span><span class="token punctuation">(</span>p2<span class="token punctuation">.</span>x<span class="token punctuation">,</span> p2<span class="token punctuation">.</span>y<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
      <span class="token keyword">break</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  context<span class="token punctuation">.</span><span class="token function">stroke</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


