<template><div><p>小程序定位问题也是一大难题，而官方提供了 LogManager 和实时日志，这两个能力是如何结合使用、是否还有更便捷的方式来使用呢？</p>
<!--more-->
<h1 id="日志与反馈" tabindex="-1"><a class="header-anchor" href="#日志与反馈" aria-hidden="true">#</a> 日志与反馈</h1>
<p>前端开发在进行某个问题定位的时候，日志是很重要的。因为机器兼容性问题、环境问题等，我们常常无法复现用户的一些bug。而微信官方也提供了较完整的日志能力，我们一起来看一下。</p>
<h2 id="用户反馈" tabindex="-1"><a class="header-anchor" href="#用户反馈" aria-hidden="true">#</a> 用户反馈</h2>
<p>小程序官方提供了用户反馈携带日志的能力，大概流程是：</p>
<ol>
<li>开发中日志打印，使用日志管理器实例 LogManager。</li>
<li>用户在使用过程中，可以在小程序的 profile 页面（【右上角胶囊】-【关于xxxx】），点击【投诉与反馈】-【功能异常】（旧版本还需要勾选上传日志），则可以上传日志。</li>
<li>在小程序管理后台，【管理】-【反馈管理】，就可以查看上传的日志（还包括了很详细的用户和机型版本等信息）。</li>
</ol>
<p>这个入口可能对于用户来说过于深入（是的，官方也发现这个问题了，所以后面有了实时日志），我们小程序也可以通过<code v-pre>button</code>组件，设置<code v-pre>openType</code>为<code v-pre>feedback</code>，然后用户点击按钮就可以直接拉起意见反馈页面了。利用这个能力，我们可以监听用户截屏的操作，然后弹出浮层引导用户主动进行反馈。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>view <span class="token keyword">class</span><span class="token operator">=</span><span class="token string">"dialog"</span> <span class="token literal-property property">wx</span><span class="token operator">:</span><span class="token keyword">if</span><span class="token operator">=</span><span class="token string">"{{isFeedbackShow}}"</span><span class="token operator">></span>
  <span class="token operator">&lt;</span>view<span class="token operator">></span>是否遇到问题？<span class="token operator">&lt;</span><span class="token operator">/</span>view<span class="token operator">></span>
  <span class="token operator">&lt;</span>button open<span class="token operator">-</span>type<span class="token operator">=</span><span class="token string">"feedback"</span><span class="token operator">></span>点击反馈<span class="token operator">&lt;</span><span class="token operator">/</span>button<span class="token operator">></span>
<span class="token operator">&lt;</span><span class="token operator">/</span>view<span class="token operator">></span>

wx<span class="token punctuation">.</span><span class="token function">onUserCaptureScreen</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token comment">// 设置弹窗出现</span>
  <span class="token keyword">this</span><span class="token punctuation">.</span><span class="token function">setData</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token literal-property property">isFeedbackShow</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="logmanager" tabindex="-1"><a class="header-anchor" href="#logmanager" aria-hidden="true">#</a> LogManager</h2>
<p>关于小程序的 LogManager，大概是非常实用又特别低调的一个能力了。它的使用方式其实和 console 很相似，提供了 log、info、debug、warn 等日志方式。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> logger <span class="token operator">=</span> wx<span class="token punctuation">.</span><span class="token function">getLogManager</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
logger<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token literal-property property">str</span><span class="token operator">:</span> <span class="token string">'hello world'</span><span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token string">'basic log'</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
logger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token literal-property property">str</span><span class="token operator">:</span> <span class="token string">'hello world'</span><span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token string">'info log'</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
logger<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token literal-property property">str</span><span class="token operator">:</span> <span class="token string">'hello world'</span><span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token string">'debug log'</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
logger<span class="token punctuation">.</span><span class="token function">warn</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token literal-property property">str</span><span class="token operator">:</span> <span class="token string">'hello world'</span><span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token string">'warn log'</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">,</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">2</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>打印的日志，从管理后台下载下来之后，也是很好懂：</p>
<div class="language-log line-numbers-mode" data-ext="log"><pre v-pre class="language-log"><code><span class="token date number">2019-6-25</span> <span class="token time number">22:11:6</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> wx<span class="token punctuation">.</span>setStorageSync api invoke
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:6</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> wx<span class="token punctuation">.</span>setStorageSync return
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:6</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> wx<span class="token punctuation">.</span>setStorageSync api invoke
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:6</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> wx<span class="token punctuation">.</span>setStorageSync return
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:6</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> <span class="token punctuation">[</span><span class="token number">v1.1.0</span><span class="token punctuation">]</span> request begin
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:6</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> <span class="token domain constant">wx.request</span> api invoke with seq <span class="token number">0</span>
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:6</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> <span class="token domain constant">wx.request</span> success callback with msg request<span class="token operator">:</span>ok with seq <span class="token number">0</span>
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:6</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> <span class="token punctuation">[</span><span class="token number">v1.1.0</span><span class="token punctuation">]</span> request done
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:7</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> wx<span class="token punctuation">.</span>navigateTo api invoke
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:7</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> page packquery<span class="token operator">/</span>pages<span class="token operator">/</span>index<span class="token operator">/</span>index onHide have been invoked
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:7</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> page packquery<span class="token operator">/</span>pages<span class="token operator">/</span>logs<span class="token operator">/</span>logs onLoad have been invoked
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:7</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> <span class="token punctuation">[</span><span class="token number">v1.1.0</span><span class="token punctuation">]</span> logs  <span class="token operator">|</span>  onShow  <span class="token operator">|</span>    <span class="token operator">|</span>  <span class="token punctuation">[</span><span class="token punctuation">]</span>
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:7</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> wx<span class="token punctuation">.</span>setStorageSync api invoke
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:7</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> wx<span class="token punctuation">.</span>setStorageSync return
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:7</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> wx<span class="token punctuation">.</span>reportMonitor api invoke
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:7</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> page packquery<span class="token operator">/</span>pages<span class="token operator">/</span>logs<span class="token operator">/</span>logs onShow have been invoked
<span class="token date number">2019-6-25</span> <span class="token time number">22:11:7</span> <span class="token punctuation">[</span>log<span class="token punctuation">]</span> wx<span class="token punctuation">.</span>navigateTo success callback with msg navigateTo<span class="token operator">:</span>ok
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>LogManager 最多保存 5M 的日志内容，超过5M后，旧的日志内容会被删除。基础库默认会把 App、Page 的生命周期函数和 wx 命名空间下的函数调用写入日志，基础库的日志帮助我们定位具体哪些地方出了问题。</p>
<h2 id="实时日志" tabindex="-1"><a class="header-anchor" href="#实时日志" aria-hidden="true">#</a> 实时日志</h2>
<p>小程序的 LogManager 有一个很大的痛点，就是必须依赖用户上报，入口又是右上角胶囊-【关于xxxx】-【投诉与反馈】-【功能异常】这么长的路径，甚至用户的反馈过程也会经常丢失日志，导致无法查问题。</p>
<p>为帮助小程序开发者快捷地排查小程序漏洞、定位问题，微信推出了实时日志功能。从基础库 2.7.1 开始，开发者可通过提供的接口打印日志，日志汇聚并实时上报到小程序后台。</p>
<p>使用方式如下：</p>
<ol>
<li>使用 wx.getRealtimeLogManager 在代码⾥⾯打⽇志。</li>
<li>可从小程序管理后台【开发】-【运维中心】-【实时日志】进入日志查询页面，查看开发者打印的日志信息。</li>
</ol>
<p>开发者可通过设置时间、微信号/OpenID、页面链接、FilterMsg内容（基础库2.7.3及以上支持setFilterMsg）等筛选条件查询指定用户的日志信息:</p>
<p><img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/wxapp-logs-1.png" alt=""></p>
<p>由于后台资源限制，实时日志使用规则如下：</p>
<ol>
<li>为了定位问题方便，日志是按页面划分的，某一个页面，在onShow到onHide（切换到其它页面、右上角圆点退到后台）之间打的日志，会聚合成一条日志上报，并且在小程序管理后台上可以根据页面路径搜索出该条日志。</li>
<li>每个小程序账号每天限制500万条日志，日志会保留7天，建议遇到问题及时定位。
一条日志的上限是5KB，最多包含200次打印日志函数调用（info、warn、error调用都算），所以要谨慎打日志，避免在循环里面调用打日志接口，避免直接重写console.log的方式打日志。</li>
<li>意见反馈里面的日志，可根据OpenID搜索日志。</li>
<li>setFilterMsg 可以设置过滤的 Msg。这个接口的目的是提供某个场景的过滤能力，例如<code v-pre>setFilterMsg('scene1')</code>，则在 MP 上可输入 scene1 查询得到该条日志。比如上线过程中，某个监控有问题，可以根据 FilterMsg 过滤这个场景下的具体的用户日志。FilterMsg 仅支持大小写字母。如果需要添加多个关键字，建议使用 addFilterMsg 替代 setFilterMsg。</li>
</ol>
<h1 id="日志开发技巧" tabindex="-1"><a class="header-anchor" href="#日志开发技巧" aria-hidden="true">#</a> 日志开发技巧</h1>
<p>既然官方提供了 LogManager 和实时日志，我们当然是两个都要用啦。</p>
<h2 id="log-js" tabindex="-1"><a class="header-anchor" href="#log-js" aria-hidden="true">#</a> log.js</h2>
<p>我们将所有日志的能力都封装在一起，暴露一个通用的接口给调用方使用：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// log.js</span>
<span class="token keyword">const</span> <span class="token constant">VERSION</span> <span class="token operator">=</span> <span class="token string">"0.0.1"</span><span class="token punctuation">;</span> <span class="token comment">// 业务代码版本号，用户灰度过程中观察问题</span>

<span class="token keyword">const</span> canIUseLogManage <span class="token operator">=</span> wx<span class="token punctuation">.</span><span class="token function">canIUse</span><span class="token punctuation">(</span><span class="token string">"getLogManager"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> logger <span class="token operator">=</span> canIUseLogManage <span class="token operator">?</span> wx<span class="token punctuation">.</span><span class="token function">getLogManager</span><span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token literal-property property">level</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">;</span>
<span class="token keyword">var</span> realtimeLogger <span class="token operator">=</span> wx<span class="token punctuation">.</span>getRealtimeLogManager <span class="token operator">?</span> wx<span class="token punctuation">.</span><span class="token function">getRealtimeLogManager</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">:</span> <span class="token keyword">null</span><span class="token punctuation">;</span>

<span class="token doc-comment comment">/**
 * <span class="token keyword">@param</span> <span class="token class-name"><span class="token punctuation">{</span>string<span class="token punctuation">}</span></span> <span class="token parameter">file</span> 所在文件名
 * <span class="token keyword">@param</span>  <span class="token class-name"><span class="token punctuation">{</span><span class="token operator">...</span>any<span class="token punctuation">}</span></span> <span class="token parameter">arg</span> 参数
 */</span>

<span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token constant">DEBUG</span><span class="token punctuation">(</span><span class="token parameter">file<span class="token punctuation">,</span> <span class="token operator">...</span>args</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span>file<span class="token punctuation">,</span> <span class="token string">" | "</span><span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>canIUseLogManage<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    logger<span class="token operator">!</span><span class="token punctuation">.</span><span class="token function">debug</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token constant">VERSION</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> file<span class="token punctuation">,</span> <span class="token string">" | "</span><span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  realtimeLogger <span class="token operator">&amp;&amp;</span> realtimeLogger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token constant">VERSION</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> file<span class="token punctuation">,</span> <span class="token string">" | "</span><span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token doc-comment comment">/**
 *
 * <span class="token keyword">@param</span> <span class="token class-name"><span class="token punctuation">{</span>string<span class="token punctuation">}</span></span> <span class="token parameter">file</span> 所在文件名
 * <span class="token keyword">@param</span>  <span class="token class-name"><span class="token punctuation">{</span><span class="token operator">...</span>any<span class="token punctuation">}</span></span> <span class="token parameter">arg</span> 参数
 */</span>
<span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token constant">RUN</span><span class="token punctuation">(</span><span class="token parameter">file<span class="token punctuation">,</span> <span class="token operator">...</span>args</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>file<span class="token punctuation">,</span> <span class="token string">" | "</span><span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>canIUseLogManage<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    logger<span class="token operator">!</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token constant">VERSION</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> file<span class="token punctuation">,</span> <span class="token string">" | "</span><span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  realtimeLogger <span class="token operator">&amp;&amp;</span> realtimeLogger<span class="token punctuation">.</span><span class="token function">info</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token constant">VERSION</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> file<span class="token punctuation">,</span> <span class="token string">" | "</span><span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token doc-comment comment">/**
 *
 * <span class="token keyword">@param</span> <span class="token class-name"><span class="token punctuation">{</span>string<span class="token punctuation">}</span></span> <span class="token parameter">file</span> 所在文件名
 * <span class="token keyword">@param</span>  <span class="token class-name"><span class="token punctuation">{</span><span class="token operator">...</span>any<span class="token punctuation">}</span></span> <span class="token parameter">arg</span> 参数
 */</span>
<span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token constant">ERROR</span><span class="token punctuation">(</span><span class="token parameter">file<span class="token punctuation">,</span> <span class="token operator">...</span>args</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span>file<span class="token punctuation">,</span> <span class="token string">" | "</span><span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>canIUseLogManage<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    logger<span class="token operator">!</span><span class="token punctuation">.</span><span class="token function">warn</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token constant">VERSION</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> file<span class="token punctuation">,</span> <span class="token string">" | "</span><span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
  <span class="token keyword">if</span> <span class="token punctuation">(</span>realtimeLogger<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    realtimeLogger<span class="token punctuation">.</span><span class="token function">error</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token constant">VERSION</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">]</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> file<span class="token punctuation">,</span> <span class="token string">" | "</span><span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">// 判断是否支持设置模糊搜索</span>
    <span class="token comment">// 错误的信息可记录到 FilterMsg，方便搜索定位</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>realtimeLogger<span class="token punctuation">.</span>addFilterMsg<span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token keyword">try</span> <span class="token punctuation">{</span>
        realtimeLogger<span class="token punctuation">.</span><span class="token function">addFilterMsg</span><span class="token punctuation">(</span>
          <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token constant">VERSION</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">] </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>file<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token constant">JSON</span><span class="token punctuation">.</span><span class="token function">stringify</span><span class="token punctuation">(</span>args<span class="token punctuation">)</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span>
        <span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span>e<span class="token punctuation">)</span> <span class="token punctuation">{</span>
        realtimeLogger<span class="token punctuation">.</span><span class="token function">addFilterMsg</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">[</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token constant">VERSION</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">] </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>file<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token comment">// 方便将页面名字自动打印</span>
<span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">getLogger</span><span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">fileName</span><span class="token operator">:</span> string</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token keyword">return</span> <span class="token punctuation">{</span>
    <span class="token function-variable function">DEBUG</span><span class="token operator">:</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter"><span class="token operator">...</span>args</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token constant">DEBUG</span><span class="token punctuation">(</span>fileName<span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token function-variable function">RUN</span><span class="token operator">:</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter"><span class="token operator">...</span>args</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token constant">RUN</span><span class="token punctuation">(</span>fileName<span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token function-variable function">ERROR</span><span class="token operator">:</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter"><span class="token operator">...</span>args</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token constant">ERROR</span><span class="token punctuation">(</span>fileName<span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>通过这样的方式，我们在一个页面中使用日志的时候，可以这么使用：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> getLogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"./log"</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> <span class="token constant">PAGE_MANE</span> <span class="token operator">=</span> <span class="token string">"page_name"</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> logger <span class="token operator">=</span> <span class="token function">getLogger</span><span class="token punctuation">(</span><span class="token constant">PAGE_MANE</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="autolog-behavior" tabindex="-1"><a class="header-anchor" href="#autolog-behavior" aria-hidden="true">#</a> autolog-behavior</h2>
<p>现在有了日志组件，我们需要在足够多的地方记录日志，才能在问题出现的时候及时进行定位。一般来说，我们需要在每个方法在被调用的时候都打印一个日志，所以这里封装了一个 autolog-behavior 的方式，每个页面（需要是 Component 方式）中只需要引入这个 behavior，就可以在每个方法调用的时候，打印日志：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// autolog-behavior.js</span>
<span class="token keyword">import</span> <span class="token operator">*</span> <span class="token keyword">as</span> Log <span class="token keyword">from</span> <span class="token string">"../utils/log"</span><span class="token punctuation">;</span>
<span class="token doc-comment comment">/**
 * 本 Behavior 会在小程序 methods 中每个方法调用前添加一个 Log 说明
 * 需要在 Component 的 data 属性中添加 PAGE_NAME，用于描述当前页面
 */</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token function">Behavior</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token function">definitionFilter</span><span class="token punctuation">(</span><span class="token parameter">defFields</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token comment">// 获取定义的方法</span>
    Object<span class="token punctuation">.</span><span class="token function">keys</span><span class="token punctuation">(</span>defFields<span class="token punctuation">.</span>methods <span class="token operator">||</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span><span class="token parameter">methodName</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
      <span class="token keyword">const</span> originMethod <span class="token operator">=</span> defFields<span class="token punctuation">.</span>methods<span class="token operator">!</span><span class="token punctuation">[</span>methodName<span class="token punctuation">]</span><span class="token punctuation">;</span>
      <span class="token comment">// 遍历更新每个方法</span>
      defFields<span class="token punctuation">.</span>methods<span class="token operator">!</span><span class="token punctuation">[</span>methodName<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">ev<span class="token punctuation">,</span> <span class="token operator">...</span>args</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>ev <span class="token operator">&amp;&amp;</span> ev<span class="token punctuation">.</span>target <span class="token operator">&amp;&amp;</span> ev<span class="token punctuation">.</span>currentTarget <span class="token operator">&amp;&amp;</span> ev<span class="token punctuation">.</span>currentTarget<span class="token punctuation">.</span>dataset<span class="token punctuation">)</span> <span class="token punctuation">{</span>
          <span class="token comment">// 如果是事件类型，则只需要记录 dataset 数据</span>
          Log<span class="token punctuation">.</span><span class="token constant">RUN</span><span class="token punctuation">(</span>defFields<span class="token punctuation">.</span>data<span class="token punctuation">.</span><span class="token constant">PAGE_NAME</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>methodName<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> invoke, event dataset = </span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> ev<span class="token punctuation">.</span>currentTarget<span class="token punctuation">.</span>dataset<span class="token punctuation">,</span> <span class="token string">"params = "</span><span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
          <span class="token comment">// 其他情况下，则都记录日志</span>
          Log<span class="token punctuation">.</span><span class="token constant">RUN</span><span class="token punctuation">(</span> defFields<span class="token punctuation">.</span>data<span class="token punctuation">.</span><span class="token constant">PAGE_NAME</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>methodName<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> invoke, params = </span><span class="token template-punctuation string">`</span></span><span class="token punctuation">,</span> ev<span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token comment">// 触发原有的方法</span>
        <span class="token function">originMethod</span><span class="token punctuation">.</span><span class="token function">call</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">,</span> ev<span class="token punctuation">,</span> <span class="token operator">...</span>args<span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们能看到，日志打印依赖了页面中定义了一个<code v-pre>PAGE_NAME</code>的 data 数据，所以我们在使用的时候可以这么处理：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> getLogger <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"../../utils/log"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> autologBehavior <span class="token keyword">from</span> <span class="token string">"../../behaviors/autolog-behavior"</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> <span class="token constant">PAGE_NAME</span> <span class="token operator">=</span> <span class="token string">"page_name"</span><span class="token punctuation">;</span>
<span class="token keyword">const</span> logger <span class="token operator">=</span> <span class="token function">getLogger</span><span class="token punctuation">(</span><span class="token constant">PAGE_NAME</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token function">Component</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">behaviors</span><span class="token operator">:</span> <span class="token punctuation">[</span>autologBehavior<span class="token punctuation">]</span><span class="token punctuation">,</span>
  <span class="token literal-property property">data</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token constant">PAGE_NAME</span><span class="token punctuation">,</span>
    <span class="token comment">// 其他数据</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token literal-property property">methods</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token comment">// 定义的方法会在调用的时候自动打印日志</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><blockquote>
<p>页面如何使用 Behavior
看看<a href="https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/component.html" target="_blank" rel="noopener noreferrer">官方文档<ExternalLinkIcon/></a>：事实上，小程序的页面也可以视为自定义组件。因而，页面也可以使用<code v-pre>Component</code>构造器构造，拥有与普通组件一样的定义段与实例方法。但此时要求对应<code v-pre>json</code>文件中包含<code v-pre>usingComponents</code>定义段。</p>
</blockquote>
<p>完整的项目可以参考<a href="https://github.com/godbasin/wxapp-typescript-demo" target="_blank" rel="noopener noreferrer">wxapp-typescript-demo<ExternalLinkIcon/></a>。</p>
<h2 id="参考" tabindex="-1"><a class="header-anchor" href="#参考" aria-hidden="true">#</a> 参考</h2>
<ul>
<li><a href="https://developers.weixin.qq.com/miniprogram/dev/api/base/debug/LogManager.html" target="_blank" rel="noopener noreferrer">LogManager<ExternalLinkIcon/></a></li>
<li><a href="https://developers.weixin.qq.com/miniprogram/dev/framework/realtimelog/" target="_blank" rel="noopener noreferrer">实时日志<ExternalLinkIcon/></a></li>
<li><a href="https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/component.html" target="_blank" rel="noopener noreferrer">Component构造器<ExternalLinkIcon/></a></li>
<li><a href="https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/behaviors.html" target="_blank" rel="noopener noreferrer">behaviors<ExternalLinkIcon/></a></li>
</ul>
<h1 id="结束语" tabindex="-1"><a class="header-anchor" href="#结束语" aria-hidden="true">#</a> 结束语</h1>
<p>使用自定义组件的方式来写页面，有特别多好用的技巧，behavior 就是其中一个比较重要的能力，大家可以发挥自己的想象力来实现很多奇妙的功能。</p>
</div></template>


