<template><div><p>最近在研究前端大型项目中要怎么管理模块间通信，本文记录研究 VSCode 中通信机制的过程，主要包括 IPC 部分吧。</p>
<!--more-->
<h1 id="electron-的-通信机制" tabindex="-1"><a class="header-anchor" href="#electron-的-通信机制" aria-hidden="true">#</a> Electron 的 通信机制</h1>
<p>我们知道 Electron 是基于 Chromium + Node.js 的架构。同样基于 Chromium + Node.js 的，还有 NW.js，我们先来看看它们之间有什么不一样吧。</p>
<h1 id="electron-与-nw-js" tabindex="-1"><a class="header-anchor" href="#electron-与-nw-js" aria-hidden="true">#</a> Electron 与 NW.js</h1>
<p>说到 Node.js 的桌面应用，基本上大家都会知道 Electron 和 NW.js。例如 VsCode 就是基于 Electron 写的，而小程序开发工具则是基于 NW.js 来开发的。</p>
<p>我们知道，Node.js 和 Chromium 的运行环境不一样，它们的 JavaScript 上下文都有一些特有的全局对象和函数。在 Node.js 中包括 module、process、require等，在 Chromium 中会有 window、 documnet等。</p>
<p>那么，Electron 和 NW.js 都分别是怎样管理 Node.js 和 Chromium 的呢？</p>
<h3 id="nw-js-内部架构" tabindex="-1"><a class="header-anchor" href="#nw-js-内部架构" aria-hidden="true">#</a> NW.js 内部架构</h3>
<p>NW.js 是最早的 Node.js 桌面应用框架，架构如图1。</p>
<p><img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/electron_ipc_1.jpg" alt="图1"></p>
<p>在 NW.js 中，将 Node.js 和 Chromium 整合在一起使用，其中做了几件事情，我们来分别看下。</p>
<ol>
<li>
<p>Node.js 和 Chromium 都使用 V8 来处理执行的 JavaScript，因此在 NW.js 中它们使用相同的 V8 实例。</p>
</li>
<li>
<p>Node.js 和 Chromium 都使用事件循环编程模式，但它们用不同的软件库（Node.js 使用 libuv，Chromium 使用 MessageLoop/Message-Pump）。NW.js 通过使 Chromium 使用构建在 libuv 之上的定制版本的 MessagePump 来集成 Node.js 和 Chromium 的事件循环（如图2）。</p>
</li>
</ol>
<p><img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/electron_ipc_3.jpg" alt="图2"></p>
<ol start="3">
<li>整合 Node.js 的上下文到 Chromium 中，使 Node.js 可用（如图3）。</li>
</ol>
<p><img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/electron_ipc_2.jpg" alt="图3"></p>
<p>因此，虽然 NW.js 整合了 Node.js 和 Chromium，但它更接近一个前端的应用开发方式（如图4），它的入口是 index.html。</p>
<p><img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/electron_ipc_0.jpg" alt="图4"></p>
<h3 id="electron-内部架构" tabindex="-1"><a class="header-anchor" href="#electron-内部架构" aria-hidden="true">#</a> Electron 内部架构</h3>
<p>Electron 强调 Chromium 源代码和应用程序进行分离，因此并没有将 Node.js 和 Chromium 整合在一起。</p>
<p>在 Electron 中，分为主进程(main process)和渲染器进程(renderer processes)：</p>
<ul>
<li>主进程：一个 Electron 应用中，有且只有一个主进程（package.json 的 main 脚本）</li>
<li>渲染进程：Electron 里的每个页面都有它自己的进程，叫作渲染进程。由于 Electron 使用了 Chromium 来展示 web 页面，所以 Chromium 的多进程架构也被使用到</li>
</ul>
<p>那么，不在一个进程当然涉及跨进程通信。于是，在 Electron 中，可以通过以下方式来进行主进程和渲染器进程的通信：</p>
<ol>
<li>利用<code v-pre>ipcMain</code>和<code v-pre>ipcRenderer</code>模块进行 IPC 方式通信，它们是处理应用程序后端（<code v-pre>ipcMain</code>）和前端应用窗口（<code v-pre>ipcRenderer</code>）之间的进程间通信的事件触发。</li>
<li>利用<code v-pre>remote</code>模块进行 RPC 方式通信。</li>
</ol>
<blockquote>
<p><code v-pre>remote</code>模块返回的每个对象（包括函数），表示主进程中的一个对象（称为远程对象或远程函数）。当调用远程对象的方法时，调用远程函数、或者使用远程构造函数 (函数) 创建新对象时，实际上是在发送同步进程消息。</p>
</blockquote>
<p>如图5，Electron 中从应用程序的后端部分到前端部分的任何状态共享（反之亦然），均通过<code v-pre>ipcMain</code>和<code v-pre>ipcRenderer</code>模块进行。这样，主进程和渲染器进程的 JavaScript 上下文将保持独立，但是可以在进程之间以显式方式传输数据。</p>
<p><img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/electron_ipc_4.jpg" alt="图5"></p>
<h1 id="vscode-的通信机制" tabindex="-1"><a class="header-anchor" href="#vscode-的通信机制" aria-hidden="true">#</a> VSCode 的通信机制</h1>
<p>VSCode 基于 Electron 进行开发的，那么我们来看看 VSCode 里的相关设计吧。</p>
<h2 id="vscode-多进程架构" tabindex="-1"><a class="header-anchor" href="#vscode-多进程架构" aria-hidden="true">#</a> VSCode 多进程架构</h2>
<p>VSCode 采用多进程架构，VSCode 启动后主要有下面的几个进程：</p>
<ul>
<li>主进程</li>
<li>渲染进程，多个，包括 Activitybar、Sidebar、Panel、Editor 等等</li>
<li>插件宿主进程</li>
<li>Debug 进程</li>
<li>Search 进程</li>
</ul>
<p>这些进程间的关系如图6：</p>
<p><img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/electron_ipc_5.png" alt="图6"></p>
<p>而在 VSCode 中，这些进程的通信方式同样包括 IPC 和 RPC 两种，如图7：</p>
<p><img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/electron_ipc_6.jpg" alt="图7"></p>
<h2 id="ipc-通信" tabindex="-1"><a class="header-anchor" href="#ipc-通信" aria-hidden="true">#</a> IPC 通信</h2>
<p>我们能看到，主进程和渲染进程的通信基础还是 Electron 的<code v-pre>webContents.send</code>、<code v-pre>ipcRender.send</code>、<code v-pre>ipcMain.on</code>。</p>
<p>我们来看看 VSCode 中具体的 IPC 通信机制设计，包括：协议、频道、连接等。</p>
<h3 id="协议" tabindex="-1"><a class="header-anchor" href="#协议" aria-hidden="true">#</a> 协议</h3>
<p>IPC 通信中，协议是最基础的。就像我们人和人之间的交流，需要使用约定的方式（语言、手语），在 IPC 中协议可看做是约定。</p>
<p>作为通信能力，最基本的协议范围包括发送和接受消息：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">export</span> <span class="token keyword">interface</span> <span class="token class-name">IMessagePassingProtocol</span> <span class="token punctuation">{</span>
	<span class="token function">send</span><span class="token punctuation">(</span>buffer<span class="token operator">:</span> VSBuffer<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span><span class="token punctuation">;</span>
	<span class="token literal-property property">onMessage</span><span class="token operator">:</span> Event<span class="token operator">&lt;</span>VSBuffer<span class="token operator">></span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>至于具体协议内容，可能包括连接、断开、事件等等：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">Protocol</span> <span class="token keyword">implements</span> <span class="token class-name">IMessagePassingProtocol</span> <span class="token punctuation">{</span>
	<span class="token function">constructor</span><span class="token punctuation">(</span><span class="token parameter"><span class="token keyword">private</span> <span class="token literal-property property">sender</span><span class="token operator">:</span> Sender<span class="token punctuation">,</span> readonly onMessage<span class="token operator">:</span> Event<span class="token operator">&lt;</span>VSBuffer<span class="token operator">></span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token punctuation">}</span>
	<span class="token comment">// 发送消息</span>
	<span class="token function">send</span><span class="token punctuation">(</span>message<span class="token operator">:</span> VSBuffer<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span>
		<span class="token keyword">try</span> <span class="token punctuation">{</span>
			<span class="token keyword">this</span><span class="token punctuation">.</span>sender<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token string">'vscode:message'</span><span class="token punctuation">,</span> message<span class="token punctuation">.</span>buffer<span class="token punctuation">)</span><span class="token punctuation">;</span>
		<span class="token punctuation">}</span> <span class="token keyword">catch</span> <span class="token punctuation">(</span>e<span class="token punctuation">)</span> <span class="token punctuation">{</span>
			<span class="token comment">// systems are going down</span>
		<span class="token punctuation">}</span>
	<span class="token punctuation">}</span>
	<span class="token comment">// 断开连接</span>
	<span class="token function">dispose</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span>
		<span class="token keyword">this</span><span class="token punctuation">.</span>sender<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token string">'vscode:disconnect'</span><span class="token punctuation">,</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们能看到，IPC 的通信也使用了 VSCode 中的<code v-pre>Event</code>/<code v-pre>Emitter</code>事件机制，关于事件的更多可以参考<a href="https://godbasin.github.io/front-end-playground/front-end-basic/deep-learning/vscode-event.html" target="_blank" rel="noopener noreferrer">《VSCode源码解读：事件系统设计》<ExternalLinkIcon/></a>。</p>
<p>IPC 实际上就是发送和接收信息的能力，而要能准确地进行通信，客户端和服务端需要在同一个频道上。</p>
<h3 id="频道" tabindex="-1"><a class="header-anchor" href="#频道" aria-hidden="true">#</a> 频道</h3>
<p>作为一个频道而言，它会有两个功能，一个是点播<code v-pre>call</code>，一个是收听，即<code v-pre>listen</code>。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token doc-comment comment">/**
 * IChannel是对命令集合的抽象
 * call 总是返回一个至多带有单个返回值的 Promise
 */</span>
<span class="token keyword">export</span> <span class="token keyword">interface</span> <span class="token class-name">IChannel</span> <span class="token punctuation">{</span>
	call<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span><span class="token punctuation">(</span>command<span class="token operator">:</span> string<span class="token punctuation">,</span> arg<span class="token operator">?</span><span class="token operator">:</span> any<span class="token punctuation">,</span> cancellationToken<span class="token operator">?</span><span class="token operator">:</span> CancellationToken<span class="token punctuation">)</span><span class="token operator">:</span> Promise<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span><span class="token punctuation">;</span>
	listen<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span><span class="token punctuation">(</span>event<span class="token operator">:</span> string<span class="token punctuation">,</span> arg<span class="token operator">?</span><span class="token operator">:</span> any<span class="token punctuation">)</span><span class="token operator">:</span> Event<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="客户端与服务端" tabindex="-1"><a class="header-anchor" href="#客户端与服务端" aria-hidden="true">#</a> 客户端与服务端</h3>
<p>一般来说，客户端和服务端的区分主要是：发起连接的一端为客户端，被连接的一端为服务端。在 VSCode 中，主进程是服务端，提供各种频道和服务供订阅；渲染进程是客户端，收听服务端提供的各种频道/服务，也可以给服务端发送一些消息（接入、订阅/收听、离开等）。</p>
<p>不管是客户端和服务端，它们都会需要发送和接收消息的能力，才能进行正常的通信。</p>
<p>在 VSCode 中，客户端包括<code v-pre>ChannelClient</code>和<code v-pre>IPCClient</code>，<code v-pre>ChannelClient</code>只处理最基础的频道相关的功能，包括：</p>
<ol>
<li>获得频道<code v-pre>getChannel</code>。</li>
<li>发送频道请求<code v-pre>sendRequest</code>。</li>
<li>接收请求结果，并处理<code v-pre>onResponse/onBuffer</code>。</li>
</ol>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 客户端</span>
<span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">ChannelClient</span> <span class="token keyword">implements</span> <span class="token class-name">IChannelClient</span><span class="token punctuation">,</span> IDisposable <span class="token punctuation">{</span>
	getChannel<span class="token operator">&lt;</span><span class="token constant">T</span> <span class="token keyword">extends</span> <span class="token class-name">IChannel</span><span class="token operator">></span><span class="token punctuation">(</span>channelName<span class="token operator">:</span> string<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span> <span class="token punctuation">{</span>
		<span class="token keyword">const</span> that <span class="token operator">=</span> <span class="token keyword">this</span><span class="token punctuation">;</span>
		<span class="token keyword">return</span> <span class="token punctuation">{</span>
			<span class="token function">call</span><span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">command</span><span class="token operator">:</span> string<span class="token punctuation">,</span> arg<span class="token operator">?</span><span class="token operator">:</span> any<span class="token punctuation">,</span> cancellationToken<span class="token operator">?</span><span class="token operator">:</span> CancellationToken</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
				<span class="token keyword">return</span> that<span class="token punctuation">.</span><span class="token function">requestPromise</span><span class="token punctuation">(</span>channelName<span class="token punctuation">,</span> command<span class="token punctuation">,</span> arg<span class="token punctuation">,</span> cancellationToken<span class="token punctuation">)</span><span class="token punctuation">;</span>
			<span class="token punctuation">}</span><span class="token punctuation">,</span>
			<span class="token function">listen</span><span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">event</span><span class="token operator">:</span> string<span class="token punctuation">,</span> <span class="token literal-property property">arg</span><span class="token operator">:</span> any</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
				<span class="token keyword">return</span> that<span class="token punctuation">.</span><span class="token function">requestEvent</span><span class="token punctuation">(</span>channelName<span class="token punctuation">,</span> event<span class="token punctuation">,</span> arg<span class="token punctuation">)</span><span class="token punctuation">;</span>
			<span class="token punctuation">}</span>
		<span class="token punctuation">}</span> <span class="token keyword">as</span> <span class="token constant">T</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">requestPromise</span><span class="token punctuation">(</span>channelName<span class="token operator">:</span> string<span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> string<span class="token punctuation">,</span> arg<span class="token operator">?</span><span class="token operator">:</span> any<span class="token punctuation">,</span> cancellationToken <span class="token operator">=</span> CancellationToken<span class="token punctuation">.</span>None<span class="token punctuation">)</span><span class="token operator">:</span> Promise<span class="token operator">&lt;</span>any<span class="token operator">></span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">requestEvent</span><span class="token punctuation">(</span>channelName<span class="token operator">:</span> string<span class="token punctuation">,</span> <span class="token literal-property property">name</span><span class="token operator">:</span> string<span class="token punctuation">,</span> arg<span class="token operator">?</span><span class="token operator">:</span> any<span class="token punctuation">)</span><span class="token operator">:</span> Event<span class="token operator">&lt;</span>any<span class="token operator">></span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">sendRequest</span><span class="token punctuation">(</span>request<span class="token operator">:</span> IRawRequest<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">send</span><span class="token punctuation">(</span>header<span class="token operator">:</span> any<span class="token punctuation">,</span> <span class="token literal-property property">body</span><span class="token operator">:</span> any <span class="token operator">=</span> <span class="token keyword">undefined</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">sendBuffer</span><span class="token punctuation">(</span>message<span class="token operator">:</span> VSBuffer<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">onBuffer</span><span class="token punctuation">(</span>message<span class="token operator">:</span> VSBuffer<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">onResponse</span><span class="token punctuation">(</span>response<span class="token operator">:</span> IRawResponse<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">whenInitialized</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> Promise<span class="token operator">&lt;</span><span class="token keyword">void</span><span class="token operator">></span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token function">dispose</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>同样的，服务端包括<code v-pre>ChannelServer</code>和<code v-pre>IPCServer</code>，<code v-pre>ChannelServer</code>也只处理与频道直接相关的功能，包括：</p>
<ol>
<li>注册频道<code v-pre>registerChannel</code>。</li>
<li>监听客户端消息<code v-pre>onRawMessage/onPromise/onEventListen</code>。</li>
<li>处理客户端消息并返回请求结果<code v-pre>sendResponse</code>。</li>
</ol>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 服务端</span>
<span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">ChannelServer</span><span class="token operator">&lt;</span>TContext <span class="token operator">=</span> string<span class="token operator">></span> <span class="token keyword">implements</span> <span class="token class-name">IChannelServer</span><span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">,</span> IDisposable <span class="token punctuation">{</span>
	<span class="token function">registerChannel</span><span class="token punctuation">(</span>channelName<span class="token operator">:</span> string<span class="token punctuation">,</span> <span class="token literal-property property">channel</span><span class="token operator">:</span> IServerChannel<span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span>
		<span class="token keyword">this</span><span class="token punctuation">.</span>channels<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span>channelName<span class="token punctuation">,</span> channel<span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">sendResponse</span><span class="token punctuation">(</span>response<span class="token operator">:</span> IRawResponse<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">send</span><span class="token punctuation">(</span>header<span class="token operator">:</span> any<span class="token punctuation">,</span> <span class="token literal-property property">body</span><span class="token operator">:</span> any <span class="token operator">=</span> <span class="token keyword">undefined</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">sendBuffer</span><span class="token punctuation">(</span>message<span class="token operator">:</span> VSBuffer<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">onRawMessage</span><span class="token punctuation">(</span>message<span class="token operator">:</span> VSBuffer<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">onPromise</span><span class="token punctuation">(</span>request<span class="token operator">:</span> IRawPromiseRequest<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">onEventListen</span><span class="token punctuation">(</span>request<span class="token operator">:</span> IRawEventListenRequest<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">disposeActiveRequest</span><span class="token punctuation">(</span>request<span class="token operator">:</span> IRawRequest<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">private</span> <span class="token function">collectPendingRequest</span><span class="token punctuation">(</span>request<span class="token operator">:</span> IRawPromiseRequest <span class="token operator">|</span> IRawEventListenRequest<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token keyword">public</span> <span class="token function">dispose</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>我们能看到，作为频道的直接连接对象，<code v-pre>ChannelClient</code>和<code v-pre>ChannelServer</code>的发送和接收基本上是一一对应的，像<code v-pre>sendRequest</code>和<code v-pre>sendResponse</code>等等。但<code v-pre>ChannelClient</code>只能发送请求，而<code v-pre>ChannelServer</code>只能响应请求，在阅读完整篇文章后，可以思考一下：如果我们想要实现双向通信的话，可以怎么做呢？</p>
<p>我们还发现，对消息的发送和接受，<code v-pre>ChannelClient</code>和<code v-pre>ChannelServer</code>会进行序列化(<code v-pre>serialize</code>)和反序列化(<code v-pre>deserialize</code>)：</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 此处篇幅关系，以 deserialize 举例：</span>
<span class="token keyword">function</span> <span class="token function">deserialize</span><span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">reader</span><span class="token operator">:</span> IReader</span><span class="token punctuation">)</span><span class="token operator">:</span> any <span class="token punctuation">{</span>
	<span class="token keyword">const</span> type <span class="token operator">=</span> reader<span class="token punctuation">.</span><span class="token function">read</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">readUInt8</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token keyword">switch</span> <span class="token punctuation">(</span>type<span class="token punctuation">)</span> <span class="token punctuation">{</span>
		<span class="token keyword">case</span> DataType<span class="token punctuation">.</span>Undefined<span class="token operator">:</span> <span class="token keyword">return</span> <span class="token keyword">undefined</span><span class="token punctuation">;</span>
		<span class="token keyword">case</span> DataType<span class="token punctuation">.</span>String<span class="token operator">:</span> <span class="token keyword">return</span> reader<span class="token punctuation">.</span><span class="token function">read</span><span class="token punctuation">(</span><span class="token function">readSizeBuffer</span><span class="token punctuation">(</span>reader<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
		<span class="token keyword">case</span> DataType<span class="token punctuation">.</span>Buffer<span class="token operator">:</span> <span class="token keyword">return</span> reader<span class="token punctuation">.</span><span class="token function">read</span><span class="token punctuation">(</span><span class="token function">readSizeBuffer</span><span class="token punctuation">(</span>reader<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span>buffer<span class="token punctuation">;</span>
		<span class="token keyword">case</span> DataType<span class="token punctuation">.</span>VSBuffer<span class="token operator">:</span> <span class="token keyword">return</span> reader<span class="token punctuation">.</span><span class="token function">read</span><span class="token punctuation">(</span><span class="token function">readSizeBuffer</span><span class="token punctuation">(</span>reader<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
		<span class="token keyword">case</span> DataType<span class="token punctuation">.</span>Array<span class="token operator">:</span> <span class="token punctuation">{</span>
			<span class="token keyword">const</span> length <span class="token operator">=</span> <span class="token function">readSizeBuffer</span><span class="token punctuation">(</span>reader<span class="token punctuation">)</span><span class="token punctuation">;</span>
			<span class="token keyword">const</span> <span class="token literal-property property">result</span><span class="token operator">:</span> any<span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>

			<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">let</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
				result<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span><span class="token function">deserialize</span><span class="token punctuation">(</span>reader<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
			<span class="token punctuation">}</span>

			<span class="token keyword">return</span> result<span class="token punctuation">;</span>
		<span class="token punctuation">}</span>
		<span class="token keyword">case</span> DataType<span class="token punctuation">.</span>Object<span class="token operator">:</span> <span class="token keyword">return</span> <span class="token constant">JSON</span><span class="token punctuation">.</span><span class="token function">parse</span><span class="token punctuation">(</span>reader<span class="token punctuation">.</span><span class="token function">read</span><span class="token punctuation">(</span><span class="token function">readSizeBuffer</span><span class="token punctuation">(</span>reader<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>那么，<code v-pre>IPCClient</code>和<code v-pre>IPCServer</code>又起到什么作用呢？</p>
<h3 id="连接" tabindex="-1"><a class="header-anchor" href="#连接" aria-hidden="true">#</a> 连接</h3>
<p>现在有了频道直接相关的客户端部分<code v-pre>ChannelClient</code>和服务端部分<code v-pre>ChannelServer</code>，但是它们之间需要连接起来才能进行通信。一个连接(<code v-pre>Connection</code>)由<code v-pre>ChannelClient</code>和<code v-pre>ChannelServer</code>组成。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">interface</span> <span class="token class-name">Connection</span><span class="token operator">&lt;</span>TContext<span class="token operator">></span> <span class="token keyword">extends</span> <span class="token class-name">Client</span><span class="token operator">&lt;</span>TContext<span class="token operator">></span> <span class="token punctuation">{</span>
	readonly channelServer<span class="token operator">:</span> ChannelServer<span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">;</span> <span class="token comment">// 服务端</span>
	readonly channelClient<span class="token operator">:</span> ChannelClient<span class="token punctuation">;</span> <span class="token comment">// 客户端</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>而连接的建立，则由<code v-pre>IPCServer</code>和<code v-pre>IPCClient</code>负责。其中：</p>
<ul>
<li><code v-pre>IPCClient</code>基于<code v-pre>ChannelClient</code>，负责简单的客户端到服务端一对一连接</li>
<li><code v-pre>IPCServer</code>基于<code v-pre>channelServer</code>，负责服务端到客户端的连接，由于一个服务端可提供多个服务，因此会有多个连接</li>
</ul>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 客户端</span>
<span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">IPCClient</span><span class="token operator">&lt;</span>TContext <span class="token operator">=</span> string<span class="token operator">></span> <span class="token keyword">implements</span> <span class="token class-name">IChannelClient</span><span class="token punctuation">,</span> IChannelServer<span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">,</span> IDisposable <span class="token punctuation">{</span>
	<span class="token keyword">private</span> <span class="token literal-property property">channelClient</span><span class="token operator">:</span> ChannelClient<span class="token punctuation">;</span>
	<span class="token keyword">private</span> <span class="token literal-property property">channelServer</span><span class="token operator">:</span> ChannelServer<span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">;</span>
	getChannel<span class="token operator">&lt;</span><span class="token constant">T</span> <span class="token keyword">extends</span> <span class="token class-name">IChannel</span><span class="token operator">></span><span class="token punctuation">(</span>channelName<span class="token operator">:</span> string<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span> <span class="token punctuation">{</span>
		<span class="token keyword">return</span> <span class="token keyword">this</span><span class="token punctuation">.</span>channelClient<span class="token punctuation">.</span><span class="token function">getChannel</span><span class="token punctuation">(</span>channelName<span class="token punctuation">)</span> <span class="token keyword">as</span> <span class="token constant">T</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
	<span class="token function">registerChannel</span><span class="token punctuation">(</span>channelName<span class="token operator">:</span> string<span class="token punctuation">,</span> <span class="token literal-property property">channel</span><span class="token operator">:</span> IServerChannel<span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span>
		<span class="token keyword">this</span><span class="token punctuation">.</span>channelServer<span class="token punctuation">.</span><span class="token function">registerChannel</span><span class="token punctuation">(</span>channelName<span class="token punctuation">,</span> channel<span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
<span class="token punctuation">}</span>

<span class="token comment">// 由于服务端有多个服务，因此可能存在多个连接</span>
<span class="token keyword">export</span> <span class="token keyword">class</span> <span class="token class-name">IPCServer</span><span class="token operator">&lt;</span>TContext <span class="token operator">=</span> string<span class="token operator">></span> <span class="token keyword">implements</span> <span class="token class-name">IChannelServer</span><span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">,</span> IRoutingChannelClient<span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">,</span> IConnectionHub<span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">,</span> IDisposable <span class="token punctuation">{</span>
	<span class="token keyword">private</span> channels <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Map</span><span class="token operator">&lt;</span>string<span class="token punctuation">,</span> IServerChannel<span class="token operator">&lt;</span>TContext<span class="token operator">>></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token keyword">private</span> _connections <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Set</span><span class="token operator">&lt;</span>Connection<span class="token operator">&lt;</span>TContext<span class="token operator">>></span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token comment">// 获取连接信息</span>
	<span class="token keyword">get</span> <span class="token function">connections</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> Connection<span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token doc-comment comment">/**
	 * 从远程客户端获取频道。
	 * 通过路由器后，可以指定它要呼叫和监听/从哪个客户端。
	 * 否则，当在没有路由器的情况下进行呼叫时，将选择一个随机客户端，而在没有路由器的情况下进行侦听时，将监听每个客户端。
	 */</span>
	getChannel<span class="token operator">&lt;</span><span class="token constant">T</span> <span class="token keyword">extends</span> <span class="token class-name">IChannel</span><span class="token operator">></span><span class="token punctuation">(</span>channelName<span class="token operator">:</span> string<span class="token punctuation">,</span> <span class="token literal-property property">router</span><span class="token operator">:</span> IClientRouter<span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span><span class="token punctuation">;</span>
	getChannel<span class="token operator">&lt;</span><span class="token constant">T</span> <span class="token keyword">extends</span> <span class="token class-name">IChannel</span><span class="token operator">></span><span class="token punctuation">(</span>channelName<span class="token operator">:</span> string<span class="token punctuation">,</span> <span class="token function-variable function">clientFilter</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">client</span><span class="token operator">:</span> Client<span class="token operator">&lt;</span>TContext<span class="token operator">></span></span><span class="token punctuation">)</span> <span class="token operator">=></span> boolean<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span><span class="token punctuation">;</span>
	getChannel<span class="token operator">&lt;</span><span class="token constant">T</span> <span class="token keyword">extends</span> <span class="token class-name">IChannel</span><span class="token operator">></span><span class="token punctuation">(</span>channelName<span class="token operator">:</span> string<span class="token punctuation">,</span> <span class="token literal-property property">routerOrClientFilter</span><span class="token operator">:</span> IClientRouter<span class="token operator">&lt;</span>TContext<span class="token operator">></span> <span class="token operator">|</span> <span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">client</span><span class="token operator">:</span> Client<span class="token operator">&lt;</span>TContext<span class="token operator">></span></span><span class="token punctuation">)</span> <span class="token operator">=></span> boolean<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">T</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
	<span class="token comment">// 注册频道</span>
	<span class="token function">registerChannel</span><span class="token punctuation">(</span>channelName<span class="token operator">:</span> string<span class="token punctuation">,</span> <span class="token literal-property property">channel</span><span class="token operator">:</span> IServerChannel<span class="token operator">&lt;</span>TContext<span class="token operator">></span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span> <span class="token punctuation">{</span>
		<span class="token keyword">this</span><span class="token punctuation">.</span>channels<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span>channelName<span class="token punctuation">,</span> channel<span class="token punctuation">)</span><span class="token punctuation">;</span>
		<span class="token comment">// 添加到连接中</span>
		<span class="token keyword">this</span><span class="token punctuation">.</span>_connections<span class="token punctuation">.</span><span class="token function">forEach</span><span class="token punctuation">(</span><span class="token parameter">connection</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
			connection<span class="token punctuation">.</span>channelServer<span class="token punctuation">.</span><span class="token function">registerChannel</span><span class="token punctuation">(</span>channelName<span class="token punctuation">,</span> channel<span class="token punctuation">)</span><span class="token punctuation">;</span>
		<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>前面也说过，客户端可理解为渲染进程，服务端可理解为主进程。</p>
<p>而连接的详细建立过程，可以参考<a href="https://juejin.im/post/6844904050052300814" target="_blank" rel="noopener noreferrer">《vscode-通信机制设计解读(Electron)》<ExternalLinkIcon/></a>一文。这里借用里面的一张图：</p>
<p><img src="https://github-imglib-1255459943.cos.ap-chengdu.myqcloud.com/electron_ipc_7.jpg" alt="图8"></p>
<h1 id="参考" tabindex="-1"><a class="header-anchor" href="#参考" aria-hidden="true">#</a> 参考</h1>
<ul>
<li><a href="https://zhaomenghuan.js.org/blog/vscode-workbench-source-code-interpretation.html" target="_blank" rel="noopener noreferrer">vscode 定制开发 —— Workbench 源码解读及实战前言<ExternalLinkIcon/></a></li>
<li><a href="https://zhaomenghuan.js.org/blog/vscode-custom-development-basic-preparation.html" target="_blank" rel="noopener noreferrer">vscode 定制开发 —— 基础准备<ExternalLinkIcon/></a></li>
<li><a href="https://livebook.manning.com/book/cross-platform-desktop-applications/chapter-6/59" target="_blank" rel="noopener noreferrer">【译】探索NW.js和Electron的内部<ExternalLinkIcon/></a></li>
<li><a href="https://juejin.im/post/6844904050052300814" target="_blank" rel="noopener noreferrer">vscode-通信机制设计解读(Electron)<ExternalLinkIcon/></a></li>
<li><a href="https://imweb.io/topic/5b3b72ab4d378e703a4f4435" target="_blank" rel="noopener noreferrer">你不知道的 Electron (一)：神奇的 remote 模块<ExternalLinkIcon/></a></li>
</ul>
<h1 id="结束语" tabindex="-1"><a class="header-anchor" href="#结束语" aria-hidden="true">#</a> 结束语</h1>
<p>IPC 和 RPC 通信是由于 Electron 的跨进程通信出现的。那么，我们还可以思考下，在一般的前端开发场景下，除了跨进程以外是否还有其他场景可以参考呢？</p>
<p>至于 RPC 的部分，由于目前也没有强业务相关，有空我们下次再约。</p>
</div></template>


